---
output: 
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```

# Extended Data Figure 4a

```{r init-workspace, echo=FALSE, message=FALSE, warning=FALSE}
# Set environment
options(StringsAsFactors = FALSE)

# Load libraries
library(RColorBrewer)
library(ggplot2)
library(VennDiagram)
library(reshape2)

# Load functions
source(file = "../src/fReorderFactorLevels.R")
```

```{r load-data}
# Load macaque starting data
load(file = "../cache/nhp_PrePost_StartingData.RData")

# Load macaque expr change (cortex by area/layer)
load(file = "../cache/expr_dynamics/expr.summary.bystruc.long_all.RData")

```


```{r process-data}
# Annotate expr rate df
match1 <- match(expr.summary.bystruc.long$struc_age, samplePrePost$struc_age)
expr.summary.bystruc.long$age <- samplePrePost$age[match1]
expr.summary.bystruc.long$toplevel <- samplePrePost$toplevel[match1]
expr.summary.bystruc.long$region <- samplePrePost$region[match1]
expr.summary.bystruc.long$subregion <- samplePrePost$subregion[match1]
expr.summary.bystruc.long$layer <- samplePrePost$layer_dev[match1]

# Keep expr rate subset
keep.struc <- with(expr.summary.bystruc.long, 
                   which(!is.na(expr_diff_rate)))  # Remove E40, etc.
expr.summary.bystruc.long <- droplevels(expr.summary.bystruc.long[keep.struc, ])

```


```{r plot-expr-dynamics, fig.width=6, fig.height=8, message=FALSE, eval=TRUE}
PlotRates <- function(expr.rate, area) {
  num.timepoints <- length(table(expr.rate$age))
  plot.title <- paste(area, "- GEX rates of change")
  
  g1 <- ggplot(expr.rate, aes(x = as.numeric(age), y = abs(expr_diff_rate), 
                              color=subregion)) + 
    facet_grid(layer~expr_diff_dir) + 
    stat_summary(fun.y = median, geom = "point") +
    stat_summary(fun.y = median, geom = "line") +
    ylab("Median doublings/halvings per year") +
    xlab("Age") +
    ggtitle(plot.title) +
    scale_x_discrete(breaks = 1:num.timepoints, 
                     labels = levels(expr.rate$age)) +
    scale_y_log10() + 
    #   scale_color_manual(values=c("#f8766d", "#619cff", "#00ba38")) +
    theme_bw() + theme(text = element_text(size = 10), 
                       axis.text.x = element_text(angle=45), 
                       strip.text.y = element_text(angle=0), 
                       panel.grid.minor = element_blank())
  return(g1)
}

# Plot TH
toplevel1 <- "TH"
expr.rate.df <- droplevels(subset(expr.summary.bystruc.long, 
                               toplevel == toplevel1))
expr.rate.df$subregion <- toplevel1
PlotRates(expr.rate.df, toplevel1)

# Plot BG
toplevel1 <- "BG"
expr.rate.df <- droplevels(subset(expr.summary.bystruc.long, 
                               toplevel == toplevel1))
expr.rate.df$subregion <- toplevel1
PlotRates(expr.rate.df, toplevel1)

# Plot AM
toplevel1 <- "AM"
expr.rate.df <- droplevels(subset(expr.summary.bystruc.long, 
                               toplevel == toplevel1))
expr.rate.df$subregion <- toplevel1
PlotRates(expr.rate.df, toplevel1)

# Plot HP
toplevel1 <- "HP"
expr.rate.df <- droplevels(subset(expr.summary.bystruc.long, 
                               toplevel == toplevel1))
PlotRates(expr.rate.df, toplevel1)

# Plot NCX
toplevel1 <- "NCX"
expr.rate.df <- droplevels(subset(expr.summary.bystruc.long, 
                               toplevel == toplevel1))
new.levels <- rev(levels(expr.rate.df$layer))
expr.rate.df$layer <- factor(expr.rate.df$layer, levels=new.levels)
PlotRates(expr.rate.df, toplevel1)

```
