---
output: 
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
# knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```


```{r init-workspace, echo=FALSE, message=FALSE, warning=FALSE}
options(stringsAsFactors = FALSE)

# Load libraries
library(ggplot2)
library(limma)

# Load functions
source(file = "../src/fReorderFactorLevels.R")

```

```{r load-data, echo=FALSE}
# Load starting data: expr, samples, and probes
load(file="../cache/nhp_PrePost_StartingData.RData")

```

```{r calc-dex}
# Try loading pre-calculated DEX
dex.fn <- "../analysis/expr_dynamics/age.dex.cnt.RData"
try(load(dex.fn), silent=TRUE)

# SLOW - Run only as needed
if (! exists("age.dex.cnt")) {

  # Calc ALL region age DEX
  age.dex.cnt <- data.frame()
  for (i in levels(samplePrePost$toplevel)) {
    for (j in levels(samplePrePost$region)) {
      print(paste(i, j, sep = "_"))
      for (k in levels(samplePrePost$subregion)) {
        for (l in levels(samplePrePost$layer_dev)) {
          keep.samples <- with(samplePrePost, which(toplevel == i &
                                                      region == j & 
                                                      subregion == k & 
                                                      layer_dev == l))
          # Check if at least 4 samples
          if (length(keep.samples) >= 4) {
            sample.subset <- droplevels(samplePrePost[keep.samples, ])
            # Check if at least 2 samples per age
            num.ages <- with(sample.subset, sum(table(age) >= 2))
            # Check if at least 2 ages
            if (num.ages >= 2) {
              expr.subset <- exprPrePost[, keep.samples]
              # DEX
              design <- model.matrix(~ 0 + sample.subset$age)
              colnames(design) <- gsub("sample.subset$", "", colnames(design), fixed = TRUE)
              age.contr <- paste(colnames(design)[-1], 
                                 colnames(design)[-ncol(design)], sep="-")
              
              fit <- lmFit(expr.subset, design)
              cont.matrix <- makeContrasts(contrasts=age.contr, levels = design) 
              
              fit2 <- eBayes(contrasts.fit(fit, cont.matrix))
              top1 <- topTable(fit2, number = Inf, p.value = 1, adjust = "BH", 
                               sort.by = "none")
              
              # Find number DEX
              dex.ages <- gsub("-", ".", age.contr, fixed=TRUE)
              # KLUDGE - rename limma column
              if (length(dex.ages) == 1) {
                colnames(top1)[1] <- dex.ages
              }
              num.incr <- vector("numeric", length(dex.ages))
              names(num.incr) <- dex.ages
              num.decr <- vector("numeric", length(dex.ages))
              names(num.decr) <- dex.ages
              for (dex1 in dex.ages) {
                num.incr[dex1] <- sum(top1[, dex1] > log2(1.25) & 
                                        top1$adj.P.Val < 0.05)
                num.decr[dex1] <- sum(top1[, dex1] < -log2(1.25) & 
                                        top1$adj.P.Val < 0.05)
              }
              # Store number DEX
              age.dex.cnt <- rbind(age.dex.cnt, 
                                  data.frame(i, j, k, l, dir="Increasing", 
                                             age=dex.ages, num.genes=num.incr), 
                                  data.frame(i, j, k, l, dir="Decreasing", 
                                             age=dex.ages, num.genes=num.decr))
            }
          }
        }
      }
    }
  }
  
  # Make gene count numeric
  age.dex.cnt$num.genes <- as.numeric(as.character(age.dex.cnt$num.genes))
  
  # KLUDGE - Remove non-adjacent age comparison
  age.dex.cnt <- droplevels(subset(age.dex.cnt, age!="ageE90.ageE70"))
  
  # Reorder ages
  age.dex.cnt$age <- as.character(age.dex.cnt$age)
  age.dex.cnt$age <- gsub("age", "", age.dex.cnt$age)
  age.dex.cnt$age <- gsub("\\..*", "", age.dex.cnt$age)
  ages <- c("E50", "E70", "E80", "E90", "E120", "0M", "3M", "12M", "48M")
  age.dex.cnt$age <- ReorderFactorLevels(age.dex.cnt$age, ages)
  
  # Reorder rate dir
  age.dex.cnt$dir <- ReorderFactorLevels(age.dex.cnt$dir, 
                                        c("Increasing", "Decreasing"))
  
  save(age.dex.cnt, file = dex.fn)
}

```


# Extended Data Figure 4
```{r dex-boxplot, fig.height=8, fig.width=4, message=FALSE}
ggplot(age.dex.cnt, aes(x=age, y=num.genes)) + 
  geom_boxplot(notch = TRUE, notchwidth = 0.7) + 
  geom_hline(yintercept=1000, color="red") + 
  facet_grid(dir~.) + 
  ylab("# significantly changing genes") + 
  xlab("Age") + 
  ggtitle("FDR < 0.05, abs FC > 1.25") +
  theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.text.x=element_text(angle=90))

```
