---
output: 
html_document:
keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
# knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```


```{r init-workspace, echo=FALSE, message=FALSE, warning=FALSE}
options(stringsAsFactors = FALSE)

# Load libraries 
library(reshape2)
library(segmented)
library(ggplot2)
library(scatterplot3d)
library(RColorBrewer)
library(limma)

# Load functions 
source(file="../src/fReorderFactorLevels.R")
source(file="../src/fConvertPcdtoEventScore.R")

```

```{r load-data, echo=FALSE}
# Load macaque starting data
load(file="../cache/nhp_PrePost_StartingData.RData")

# Load human starting data
load(file="../lib/human/brainspan_longitudinal.RData")

# Load rat starting data (frontal cortex, hippo, hypothal, Stearn et al. 2006)
rat.dev <- read.csv(file="../lib/Stead2006/Stead_S2_nodupes_mean.csv", header=TRUE, row.names=1) 

```

```{r process-data}
#######
# Macaque
#######
# Keep subset of macaque samples
m.region <- "ACG"  # ACG / V1
keep.samples <- which(samplePrePost$subregion == m.region)
# keep.samples <- which(samplePrePost$region == m.region)
sample.subset <- droplevels(samplePrePost[keep.samples, ])
expr.subset <- exprPrePost[, keep.samples]

age.logpcd <- factor(sample.subset$age_log2pcd)

# Calculate mean expression by age (macaque)
expr.mean <- t(apply(expr.subset, 1, function(x)
  tapply(x, age.logpcd, mean)))
age.levels <- as.numeric(levels(age.logpcd))

# Relabel macaque genes with human orthologs
rownames(expr.mean) <- probes$human_genesymbol

# Calc most variable genes (macaque)
expr.var <- apply(expr.mean, 1, sd)
expr.range <- apply(expr.mean, 1, function(x) max(x) - min(x))

########
# Human
########
# Calculate mean expression by age (human)
h.region <- "MFC"  # MFC / V1C
h.age <- numAge2[age2]
h.keep.samples <- which(reg2 == h.region)
# h.keep.samples <- which(reg2 == h.region & h.age <= 6000) # Remove later ages
h.age.logpcd <- factor(round(log2(h.age[h.keep.samples]), 2))
dat2.subset <- dat2[, h.keep.samples]
h.expr.mean <- t(apply(dat2.subset, 1, function(x) tapply(x, h.age.logpcd, mean)))
# Remove genes without variation
h.sd <- apply(h.expr.mean, 1, sd)
h.expr.mean <- h.expr.mean[h.sd > 0, ]
h.age.levels <- as.numeric(levels(h.age.logpcd))


#######
# Rat
#######
rat.region <- "CTX"
# Age in pcd (21 day gestation)
rat.age <- factor(log2(c(16, 17, 18, 20, 23, 26, 29, 36, 43, 52, 112, # CTX
                         23, 26, 29, 36, 43, 52, 112,                 # HPC
                         18, 20, 23, 26, 29, 36, 43, 52, 112)))       # HYP
keep.cols <- grep(rat.region, colnames(rat.dev))
rat.expr.mean <- as.matrix(rat.dev[, keep.cols])
colnames(rat.expr.mean) <- round(as.numeric(as.character(rat.age[keep.cols])), 3)
rat.age.levels <- as.numeric(levels(droplevels(rat.age[keep.cols])))


# Get number of genes
num.genes <- nrow(expr.mean)
h.num.genes <- nrow(h.expr.mean)
rat.num.genes <- nrow(rat.dev)

# Keep macaque/human/rat orthologs and match gene order
ortho.genes <- Reduce(intersect, list(rownames(expr.mean), 
                                      rownames(h.expr.mean), 
                                      rownames(rat.expr.mean)))
ortho.genes <- sort(ortho.genes)
keep.genes <- match(ortho.genes, rownames(expr.mean))
expr.mean.subset <- expr.mean[keep.genes, ]

h.keep.genes <- match(ortho.genes, rownames(h.expr.mean))
h.expr.mean.subset <- h.expr.mean[h.keep.genes, ]

rat.keep.genes <- match(ortho.genes, rownames(rat.expr.mean))
rat.expr.mean.subset <- rat.expr.mean[rat.keep.genes, ]

# Calc expr z-scores
expr.mean.subsetz <- t(apply(expr.mean.subset, 1, scale))
colnames(expr.mean.subsetz) <- colnames(expr.mean.subset)

h.expr.mean.subsetz <- t(apply(h.expr.mean.subset, 1, scale))
colnames(h.expr.mean.subsetz) <- colnames(h.expr.mean.subset)

rat.expr.mean.subsetz <- t(apply(rat.expr.mean.subset, 1, scale))
colnames(rat.expr.mean.subsetz) <- colnames(rat.expr.mean.subset)

# Store data in lists
species.expr <- list(expr.mean.subset, 
                     h.expr.mean.subset, 
                     rat.expr.mean.subset)
names(species.expr) <- c("macaque", "human", "rat")

species.exprz <- list(expr.mean.subsetz, 
                      h.expr.mean.subsetz, 
                      rat.expr.mean.subsetz)
names(species.exprz) <- c("macaque", "human", "rat")
```


```{r fit-expr-trend, warning=FALSE}
lseg.fn <- paste0("../cache/dev_expr_species/species.lseg.all_", 
                  m.region, ".RData") 

# Try loading cached fits
try(load(lseg.fn), silent=TRUE)

# SLOW - Run only as needed
if (! exists("species.lseg.all")) {
  
  # Trap lseg warnings
  options(warn=2)
  
  # Define functions
  CalcSigSlope <- function(x) {
    slope.est <- x[1]
    slope.se <- x[2]
    # Check if 95% CI of slope est. contains zero
    slope.sign <- sign((slope.est - 1.96 * slope.se) * 
                         (slope.est + 1.96 * slope.se))
    return(slope.sign == 1)
  }
  
  # Init vars
  species.lseg.all <- vector("list", 3)
  names(species.lseg.all) <- names(species.exprz)
  
  # Fit gene trends (use non-transformed ages)
  for (species1 in names(species.lseg.all)) {
    age.levels <- 2^as.numeric(colnames(species.exprz[[species1]]))
    # Guess initial breakpoint(s) at a specific developmental age based on species
    bp1 <- 2^ConvertPcdtoEventScore(0.5, "eventScore", species1)  # 1 breakpoint
    lseg.list <- list()
    
    for (gene1 in ortho.genes) {
      expr1 <- species.exprz[[species1]][gene1, ]
      lm1 <- lm(expr1 ~ age.levels)
      # Fit 1 breakpoint
      lseg <- try(segmented(lm1, seg.Z=~age.levels, psi=list(age.levels = bp1)), 
                  silent=TRUE)
      #       errmsg <- geterrmessage()
      # Check if breakpoint(s) are too close to end of age range
      if (class(lseg)[1] == "try-error") {  # grepl("too close", errmsg)
        lseg.summary <- rep(NA, 7)
      } else {
        # Variance explained by segmented fit
        lseg.r2 <- summary(lseg)$r.sq
        # Breakpoint location(s), SE
        lseg.bp <- lseg$psi
        # Slope(s), SE
        lseg.slope <- as.vector(matrix(t(slope(lseg)$age.levels[, 1:2]), nrow=1))
        # Save gene information
        lseg.summary <- c(lseg.r2, lseg.bp[2:3], lseg.slope)
      }
      lseg.list[[gene1]] <- lseg.summary
    }
    # Combine info into data frame
    lseg.all <- as.data.frame(do.call("rbind", lseg.list))
    
    # Add column names
    colnames(lseg.all) <- c("r2", "bp", "bpse", "slope1", "slope1se", 
                            "slope2", "slope2se")
    
    # Add gene names
    lseg.all$gene <- rownames(lseg.all)
    
    # Check slope significance
    lseg.all$slope1sig <- apply(lseg.all[, c("slope1", "slope1se")], 1, 
                                CalcSigSlope)
    lseg.all$slope2sig <- apply(lseg.all[, c("slope2", "slope2se")], 1, 
                                CalcSigSlope)
    
    # Convert slope to doublings/halvings per year
    year.diff <- (lseg.all$bp - (lseg.all$bp - 1)) / 365
    lseg.all$slope1_year <- lseg.all$slope1 / year.diff
    
    # Calc breakpoint event score
    lseg.all$bp_escore <- ConvertPcdtoEventScore(log2(lseg.all$bp), species1)
    
    species.lseg.all[[species1]] <- lseg.all
  }
  
  # Restore default warnings
  options(warn=0)
  
  # Save expr fits
  save(species.lseg.all, file=lseg.fn)
  
}

```


```{r fit-dev-trend}
dev.pred.fn <- paste0("../cache/dev_expr_species/dev.expr_dev.pred_", 
                      m.region, ".RData")

# Try loading cached fits
try(load(dev.pred.fn), silent=TRUE)

# SLOW - Run only as needed
if (! exists("dev.pred")) {
  
  # Combine species data
  dev.expr <- rbind(data.frame(species="macaque", melt(expr.mean.subset), 
                               exprz=melt(expr.mean.subsetz)$value), 
                    data.frame(species="human", melt(h.expr.mean.subset), 
                               exprz=melt(h.expr.mean.subsetz)$value), 
                    data.frame(species="rat", melt(rat.expr.mean.subset), 
                               exprz=melt(rat.expr.mean.subsetz)$value))
  colnames(dev.expr) <- c("species", "gene", "log2pcd", "expr", "exprz")
  
  # Calc Translating Time escore
  dev.expr$escore <- apply(dev.expr, 1, 
                           function(x) ConvertPcdtoEventScore(as.numeric(x["log2pcd"]), 
                                                              x["species"]))
  dev.expr$escore <- round(dev.expr$escore, 2)
  
  # Calc spline fit
  # Select escores that are near all 3 species
  escore1 <- c(0.27, 0.36, 0.46, 0.54, 0.75, 0.85, 0.96, 1.32)
  dev.pred <- list()
  for (species1 in c("macaque", "human", "rat")) {
    species.dev <- subset(dev.expr, species==species1)
    pred.df <- NULL
    for (i in 1:length(ortho.genes)) {
      # Select rows corresponding to each gene
      gene.row <- seq(i, nrow(species.dev), by=length(ortho.genes))
      gene.dev <- species.dev[gene.row, ]
      
      # Fit expr trend
      gene.lo <- loess(expr ~ escore, gene.dev, degree=1)
      expr.pred <- predict(gene.lo, data.frame(escore = escore1))
      pred.df <- rbind(pred.df, expr.pred)
    }
    rownames(pred.df) <- ortho.genes
    dev.pred[[species1]] <- pred.df
  }
  
  # Save expr fits
  save(dev.expr, dev.pred, file=dev.pred.fn)
  
}

# Calc species variation
rh.var <- apply(dev.pred[["macaque"]], 1, function(x) sd(x) / mean(x)) 
h.var <- apply(dev.pred[["human"]], 1, function(x) sd(x) / mean(x))
rat.var <- apply(dev.pred[["rat"]], 1, function(x) sd(x) / mean(x))

```


```{r calc-species-cor}
# Calc species expr correlation
cor.method <- "pearson"
cor.all <- NULL
pval.all <- NULL
for (gene1 in ortho.genes) {
  cor1 <- cor.test(dev.pred[["macaque"]][gene1, ], dev.pred[["human"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor2 <- cor.test(dev.pred[["macaque"]][gene1, ], dev.pred[["rat"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor3 <- cor.test(dev.pred[["human"]][gene1, ], dev.pred[["rat"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor.all <- rbind(cor.all, c(cor1$est, cor2$est, cor3$est))
  pval.all <- rbind(pval.all, c(cor1$p.val, cor2$p.val, cor3$p.val))
}
rownames(cor.all) <- ortho.genes
colnames(cor.all) <- c("macaque-human", "macaque-rat", "human-rat")
rownames(pval.all) <- ortho.genes
colnames(pval.all) <- c("macaque-human", "macaque-rat", "human-rat")

save(cor.all, file = "../cache/dev_expr_species/cor.all_hrhrat.RData")
```


# Figure 6a
```{r calc-cor-summary, fig.width=5, fig.height=5}
# Calc species variation
rh.var <- apply(dev.pred[["macaque"]], 1, sd) 

# Keep genes that are variable
var.genes <- which(rh.var > median(rh.var))
# print(length(var.genes))
cor.subset <- cor.all[var.genes, ]

# Save correlations
# write.csv(data.frame(cor.subset), file="devcor.csv")

cor.subsetl <- melt(cor.subset)

# Plot Venn diagram of conserved dev expr trends
venn.matrix <- cor.subset
venn.matrix[1:length(venn.matrix)] <- 0
venn.matrix[cor.subset > 0.5] <- 1
vennDiagram(vennCounts(venn.matrix), cex=0.7)

```


```{r define-gene-sets}
syn.db <- read.csv(file = "../lib/SynaptomeDB/synaptome_db.csv")
syn.genes <- probes$human_genesymbol[probes$human_entrezid %in% 
                                       syn.db$gene_id]

# Define subsets of genes by conservation type
kTests <- c("rat", "human", "macaque", "conserved", "not-conserved")
gene.list <- vector("list", 5)
names(gene.list) <- kTests

for (col1 in 1:5) {
  if (col1 %in% 1:3) {
    keep.genes <- names(which(cor.subset[, col1] > 0.5 & 
                                (apply(cor.subset[, -col1], 1, 
                                       function(x) all(x <= 0.5)))))
  } else if (col1 == 4) {
    keep.genes <- names(which(apply(cor.subset, 1, function(x) sum(x > 0.5) >= 2)))
  } else if (col1 == 5) {
    keep.genes <- names(which(apply(cor.subset, 1, function(x) all(x <= 0.5))))
  }
  
  # Store gene list
  gene.list[[col1]] <- keep.genes
  
}

# Save gene lists
save(gene.list, file = "../cache/dev_expr_species/gene.list.RData")
# fn1 <- "../analysis/dev_expr_cross_species/dev_expr_conservation_sets.csv"
# write.csv(unlist(gene.list), file=fn1)

```


# Figure 6c & Extended Data Figure 7a (left)
```{r plot-gene-with-fit, fig.width=4, fig.height=4, eval=TRUE}
plot.species <- c("human", "macaque", "rat")

# Define palettes
pal1 <- brewer.pal(3, "Dark2")
# Change color alpha
alpha1 <- 0.5
pal2 <- sapply(pal1, 
               function(x) do.call(rgb, c(as.list(col2rgb(x) / 255), alpha1)))
names(pal1) <- plot.species
names(pal2) <- plot.species
pch1 <- c(16, 17, 15)
names(pch1) <- plot.species

genes <- c("SYT7", "OLIG1", "HMMR")
for (gene1 in genes) {
  # Find z-score range
  ymin <- min(sapply(species.exprz, function(x) min(x[gene1, ], na.rm=TRUE)))
  ymax <- max(sapply(species.exprz, function(x) max(x[gene1, ], na.rm=TRUE)))
  
  # Find expected ages for rhesus
  species1 <- "macaque"
  age1 <- 2^as.numeric(colnames(species.exprz[[species1]]))
  expr1 <- species.exprz[[species1]][gene1, ]
  lm1 <- lm(expr1 ~ age1)
  
  # Guess initial breakpoint(s) at a specific developmental age
  bp1 <- 2^ConvertPcdtoEventScore(0.5, "eventScore", species1)  # 1 breakpoint
  
  # Fit 1 breakpoint
  cnt <- 0
  repeat {
    cnt <- cnt + 1
    lseg <- try(segmented(lm1, seg.Z=~age1, psi=list(age1 = bp1)), 
                silent=TRUE)
    # Try fitting 10 times
    if (class(lseg)[1] != "try-error" | cnt == 10) break
  }
  rh.bp <- lseg$psi[2]
  
  # Plot fits
  for (species1 in plot.species) {
    age1 <- 2^as.numeric(colnames(species.exprz[[species1]]))
    expr1 <- species.exprz[[species1]][gene1, ]
    lm1 <- lm(expr1 ~ age1)
    
    # Guess initial breakpoint(s) at a specific developmental age
    bp1 <- 2^ConvertPcdtoEventScore(0.5, "eventScore", species1)  # 1 breakpoint
    
    # Fit 1 breakpoint
    cnt <- 0
    repeat {
      cnt <- cnt + 1
      lseg <- try(segmented(lm1, seg.Z=~age1, psi=list(age1 = bp1)), 
                  silent=TRUE)
      # Try fitting 10 times
      if (class(lseg)[1] != "try-error" | cnt == 10) break
    }
    
    # Plot fit
    if (species1 == "human") {
      plot(age1, expr1, log="x", xlim=c(10, 35000), ylim=c(ymin, ymax), 
           type="n", xaxt="n", las=1,
           xlab="Age (pcd)", ylab="Expression (z-score)", main=gene1)
      axis(1, at=c(10, 100, 1000, 10000), labels=c(10, 100, 1000, 10000))
    }
    
    if (species1 != "macaque") {
      exp.bp <- 2^ConvertPcdtoEventScore(log2(rh.bp), speciesIn = "macaque", 
                                         speciesOut = species1)
      abline(v=exp.bp, col=pal2[species1], lty="dotted", lwd=2)
    }
    abline(v=lseg$psi[2], col=pal1[species1], lty="dashed", lwd=2)
    points(age1, expr1, col=pal2[species1], pch=pch1[species1])
    plot(lseg, col=pal1[species1], add=TRUE, rug=FALSE, lwd=3)
  }
}

```


# Extended Data Figure 7b
```{r plot-species-syn-density, fig.width=4, fig.height=4}
syndens.fn <- "../lib/synaptic_density/Species synaptic density estimates.csv"
syndens <- read.csv(file=syndens.fn, header=TRUE)
keep.areas <- c("visual", "prefrontal")
keep.species <- list(c("human", "macaque", "rat"), c("human", "macaque"))
names(keep.species) <- keep.areas

syndens.area <- list()
for (area1 in keep.areas) {
  syndens.area[[area1]] <- subset(syndens, species %in% keep.species[[area1]] &
                                    area_vol == area1 & 
                                    plot == "yes")
}

# Define palettes
pal1 <- brewer.pal(3, "Dark2")
# Change color alpha
alpha1 <- 0.5
pal2 <- sapply(pal1, 
               function(x) do.call(rgb, c(as.list(col2rgb(x) / 255), alpha1)))
names(pal1) <- keep.species[["visual"]]
names(pal2) <- keep.species[["visual"]]
pch1 <- c(16, 17, 15)
names(pch1) <- keep.species[["visual"]]

# Init vars
syndens.peak <- list()
syndens.se <- list()

for (area1 in names(syndens.area)) {
  syndens.subset <- syndens.area[[area1]]
  for (species1 in keep.species[[area1]]) {
    syndens.sp <- subset(syndens.subset, species == species1)
    age1 <- syndens.sp$age_pcd
    dens1 <- syndens.sp$syn_dens_pct_max
    
    # Linear fit
    lm1 <- lm(dens1 ~ age1)
    
    # Guess initial breakpoint(s) at a specific developmental age
    bp1 <- quantile(age1, 0.25)
    
    # Fit 1 breakpoint
    cnt <- 0
    repeat {
      cnt <- cnt + 1
      lseg <- try(segmented(lm1, seg.Z=~age1, psi=list(age1 = bp1)), 
                  silent=TRUE)
      # Try fitting 10 times
      if (class(lseg)[1] != "try-error" | cnt == 10) break
    }
    
    # Store breakpoint and error
    syndens.peak[[area1]][[species1]] <- lseg$psi[2]
    syndens.se[[area1]][[species1]] <- lseg$psi[3]
    
    # Plot data and fit
    if (species1 == "human") {
      plot(age1, dens1, log="x", xlim=c(10, 35000), ylim=c(0, 100),
           type="n", xaxt="n", las=1,
           xlab="Age (post-conceptional days)", ylab="Synaptic density (% max)", 
           main=area1)
      axis(1, at=c(10, 100, 1000, 10000), labels=c(10, 100, 1000, 10000))
    }
    
    abline(v=lseg$psi[2], col=pal1[species1], lty="dashed", lwd=2)
    points(age1, dens1, col=pal2[species1], pch=pch1[species1])
    plot(lseg, col=pal1[species1], add=TRUE, rug=FALSE, lwd=3)
  }
}

```


# Figure 6e (left), Extended Data Figure 7d
```{r plot-species-comparison, fig.width=5, fig.height=15}
# Combine species data
species.lseg.long <- do.call("rbind", species.lseg.all)
species.lseg.long$species <- rep(names(species.lseg.all), 
                                 each=nrow(species.lseg.long) / 3)

# Filter genes
filter.incr <- NULL
filter.decr <- NULL
for (i in 1:nrow(species.lseg.long)) {
  x1 <- species.lseg.long[i, ]
  filter1 <- x1["r2"] > 0.8 &  # Good fit
    (x1["slope1"] > 0 &
       x1["slope1sig"] == TRUE) &  # Significant slope
    x1["gene"] %in% gene.list[["conserved"]]  # Cons. genes only
  filter2 <- x1["r2"] > 0.8 &  # Good fit
    (x1["slope1"] < 0 &
       x1["slope1sig"] == TRUE) &  # Significant slope
    x1["gene"] %in% gene.list[["conserved"]]  # Cons. genes only
  filter.incr <- c(filter.incr, filter1)
  filter.decr <- c(filter.decr, filter2)
}

# Include genes that pass filters in all 3 species
gene.sym <- species.lseg.long$gene[filter.incr]
incr.genes <- names(table(gene.sym))[table(gene.sym) == 3]
gene.sym <- species.lseg.long$gene[filter.decr]
decr.genes <- names(table(gene.sym))[table(gene.sym) == 3]
incr.decr <- list(incr.genes, decr.genes)
names(incr.decr) <- c("incr", "decr")

for (set1 in 1) {  # Plot increasing genes only
  keep.genes <- incr.decr[[set1]]
  
  # Pairs
  keep.rows <- with(species.lseg.long, which(gene %in% keep.genes))
  bp.df <- dcast(species.lseg.long[keep.rows, ], 
                 gene ~ species, value.var="bp")
  bpse.df <- dcast(species.lseg.long[keep.rows, ], 
                   gene ~ species, value.var="bpse")
  
  cor(bp.df[, -1], method="spearman")
  
  # Calc species bp differences
  bp.df2 <- data.frame(human=sapply(log2(bp.df$human), ConvertPcdtoEventScore, 
                                    "human", "eventScore"), 
                       macaque=sapply(log2(bp.df$macaque), ConvertPcdtoEventScore, 
                                      "macaque", "eventScore"), 
                       rat=sapply(log2(bp.df$rat), ConvertPcdtoEventScore, 
                                  "rat", "eventScore"))
  
  bp.diff <- cbind(bp.df2$human - bp.df2$macaque, 
                   bp.df2$human - bp.df2$rat, 
                   bp.df2$macaque - bp.df2$rat)
  rownames(bp.diff) <- bp.df$gene
  colnames(bp.diff) <- c("human-macaque", "human-rat", "macaque-rat")
  
  # Identify outliers
  slope2.chg.nonsyn <- list()
  slope2.chg.syn <- list()
  slope2.sig.incr <- with(species.lseg.all[["human"]], 
                          gene[which(slope2 > 0  & slope2sig == TRUE)])
  slope2.sig.decr <- with(species.lseg.all[["human"]],
                          gene[which(slope2 < 0  & slope2sig == TRUE)])
  slope2.chg.nonsyn[["incr"]] <- which(bp.df$gene %in% setdiff(slope2.sig.incr, syn.genes))
  slope2.chg.nonsyn[["decr"]] <- which(bp.df$gene %in% setdiff(slope2.sig.decr, syn.genes))
  slope2.chg.syn[["incr"]] <- which(bp.df$gene %in% intersect(slope2.sig.incr, syn.genes))
  slope2.chg.syn[["decr"]] <- which(bp.df$gene %in% intersect(slope2.sig.decr, syn.genes))
  
  # Identify non-outliers
  slope2.nochg.syn <- which(bp.df$gene %in% setdiff(syn.genes, unlist(slope2.chg.syn)))
  
  # Plot breakpoint comparison
  ages <- list()
  ages[[1]] <- seq(0, 2, by=0.2)  # Event score range
  ages[["human"]] <- 2^sapply(ages[[1]], function(x) ConvertPcdtoEventScore(x, "eventScore", "human"))
  ages[["macaque"]] <- 2^sapply(ages[[1]], function(x) ConvertPcdtoEventScore(x, "eventScore", "macaque"))
  ages[["rat"]] <- 2^sapply(ages[[1]], function(x) ConvertPcdtoEventScore(x, "eventScore", "rat"))
  
  plot.cols <- list(c("macaque", "human"), 
                    c("rat", "human"), 
                    c("rat", "macaque"))
  par(mfrow=c(3, 1), mar=c(5, 4, 4, 2))
  for (i in 1:length(plot.cols)) {
    cols1 <- plot.cols[[i]]
    bp1 <- bp.df[, cols1]
    bpse1 <- bpse.df[, cols1]
    bpmin <- bp1 - bpse1
    bpmax <- bp1 + bpse1
    
    # Calc breakpoint correlation between species
    cor1 <- round(cor(bp.df[, cols1], method="spearman")[1, 2], 2)
    
    # Plot breakpoint species pair comparison
    plot(bp1, log="xy", type="n", main=paste("r =", cor1), las=1, 
         cex.axis=1.2, cex.lab=1.2, 
         xlim=c(min(bpmin[, 1]), max(bpmax[, 1])), # Axes should contain SEs
         ylim=c(min(bpmin[, 2]), max(bpmax[, 2])))
    
    # Breakpoint SEs
    segments(bpmin[, 1], bp1[, 2], bpmax[, 1], bp1[, 2], col="grey90")
    segments(bp1[, 1], bpmin[, 2], bp1[, 1], bpmax[, 2], col="grey90")
    
    # Plot all gene breakpoints
    points(bp.df[, cols1], pch=19, col="grey90")
    
    # Dev equivalent ages (Translating Time)
    ages.x <- ages[[cols1[1]]]
    ages.y <- ages[[cols1[2]]]
    lines(ages.x, ages.y)
    lines(ages.x[-length(ages[[2]])], ages.y[-1], lty="dashed")
    lines(ages.x[-1], ages.y[-length(ages[[2]])], lty="dashed")
    
    # Highlight genes with sig 2nd slope
    # Incr
    text(bp.df[slope2.chg.nonsyn[["incr"]], cols1], 
         labels=bp.df[slope2.chg.nonsyn[["incr"]], "gene"],
         pch=19, col="red", cex=1, font=2)
    # Decr
    text(bp.df[slope2.chg.nonsyn[["decr"]], cols1], 
         labels=bp.df[slope2.chg.nonsyn[["decr"]], "gene"],
         pch=19, col="blue", cex=1, font=2)
    
    # Label syn genes
    # Incr
    text(bp.df[slope2.chg.syn[["incr"]], cols1], 
         labels=bp.df[slope2.chg.syn[["incr"]], "gene"],
         pch=19, col="red", cex=1, font=2)
    # Decr
    text(bp.df[slope2.chg.syn[["decr"]], cols1], 
         labels=bp.df[slope2.chg.syn[["decr"]], "gene"],
         pch=19, col="blue", cex=1, font=2)
  }
  
}

```


# Extended Data Figure 7a (right) & Figure 6c
```{r plot-species-bp-hist, fig.width=5, fig.height=5, warning=FALSE}
# Init var
species.lseg.long2 <- data.frame()
reg.genes <- list()

for (reg1 in c("ACG", "V1")) {
  # Load cached fits
  lseg.fn <- paste0("../cache/dev_expr_species/species.lseg.all_", 
                    reg1, ".RData")
  load(lseg.fn)
  
  # Combine species data
  species.lseg.long <- do.call("rbind", species.lseg.all)
  species.lseg.long$species <- rep(names(species.lseg.all), 
                                   each=nrow(species.lseg.long) / 3)
  species.lseg.long <- na.omit(species.lseg.long)
  
  # Remove rat when comparing V1
  if (reg1 == "V1") {
    species.lseg.long <- subset(species.lseg.long, species != "rat")
  }
  
  # Combine region info
  species.lseg.long$region <- reg1
  species.lseg.long2 <- rbind(species.lseg.long2, species.lseg.long)
}

# Save breakpoints for incr/decr genes
# write.csv(subset(species.lseg.long2, gene %in% c(incr.genes, decr.genes)), 
#           file="../analysis//dev_expr_cross_species/species.lseg.long_V1_ACG.csv", 
#           row.names=FALSE)


# Plot decreasing gene histograms
all.decr <- subset(species.lseg.long2, gene %in% incr.decr[["decr"]])
g.decr <- ggplot(all.decr, aes(x=bp, color=species, fill=species)) +
  facet_grid(region ~ .) +
  geom_density(adjust=1.0, alpha=0.5, size=1, fill=NA) +
  scale_x_log10(limits=c(10, 2000), breaks=c(10, 100, 1000)) +
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2") +
  xlab("Age (post-conceptional days)") +
  ylab("Density") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
plot(g.decr)

# Label synaptic and non-syn genes
keep.genes <- incr.decr[["incr"]]
all1 <- subset(species.lseg.long2, gene %in% keep.genes)
syn1 <- subset(species.lseg.long2, gene %in% intersect(keep.genes, syn.genes))
species.lseg.subset <- rbind(cbind(set="all", all1), 
                             cbind(set="syn", syn1))

# Define df of estimated peak synaptic density by species / cortical area
# print(syndens.peak)

# Copy estimate of syn dens for rat visual to prefrontal ctx
syndens.peak[["prefrontal"]][["rat"]] <- syndens.peak[["visual"]][["rat"]]
syndens.se[["prefrontal"]][["rat"]] <- syndens.se[["visual"]][["rat"]]

syndens.df <- data.frame(set=rep("all"), 
                         region=rep(c("V1", "ACG"), each = 3),
                         species=rep(names(syndens.peak[[1]]), 2),
                         bp=unlist(syndens.peak), 
                         bpmin=unlist(syndens.peak) -  # 95% CI
                           (1.96 * unlist(syndens.se)),
                         bpmax=unlist(syndens.peak) + 
                           (1.96 * unlist(syndens.se)))

# Plot histogram of breakpoints by species / cortical area
pal1 <- brewer.pal(3, "Dark2")
names(pal1) <- c("human", "macaque", "rat")
ghist1 <- ggplot(species.lseg.subset,
                 aes(x=bp, color=species, fill=species, linetype=set)) +
  facet_grid(region ~ .) +
  geom_density(adjust=1.0, alpha=0.5, size=1, fill=NA) +
  geom_rect(aes(xmin=bpmin, xmax=bpmax, ymin=0, ymax=Inf), data=syndens.df, 
            alpha=0.15, color=NA) +
  scale_x_log10(limits=c(10, 2000), breaks=c(10, 100, 1000)) +
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2") +
  xlab("Age (post-conceptional days)") +
  ylab("Density") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

plot(ghist1)

```


# Extended Data Figure 7c
```{r bp-dist-analysis, fig.width=4, fig.height=4, warning=FALSE}
# Test for sig diff between V1/ACG breakpoints
all1w <- dcast(all1, gene ~ species + region, value.var="bp")

# par(mfrow=c(1, 2))
# Macaque
wilcox.test(all1w$macaque_ACG, all1w$macaque_V1, paired=TRUE)
plot(all1w$macaque_ACG, all1w$macaque_V1, type="n", log="xy", las=1, xaxt="n",  
     main="Macaque", 
     xlab="Prefrontal breakpoint (pcd)", 
     ylab="V1 breakpoint (pcd)")
axis(1, c(100, 200, 300, 400), c(100, 200, 300, 400))
abline(a=0, b=1)
with(all1w, text(macaque_ACG, macaque_V1, gene, cex=0.5))
with(subset(all1w, gene %in% syn.genes), text(macaque_ACG, macaque_V1, gene, 
                                              cex=0.5, col="red", font=2))

# Human
wilcox.test(all1w$human_ACG, all1w$human_V1, paired=TRUE)
plot(all1w$human_ACG, all1w$human_V1, type="n", log="xy", las=1, 
     main="Human",
     xlab="Prefrontal breakpoint (pcd)", 
     ylab="")
abline(a=0, b=1)
with(all1w, text(human_ACG, human_V1, gene, cex=0.5))
with(subset(all1w, gene %in% syn.genes), text(human_ACG, human_V1, gene, 
                                              cex=0.5, col="red", font=2))

save.image(file = "../workspace.RData")
```

# Figure 6e (right)
```{r compare-breakpoints, warning=FALSE}
# Load breakpoints for increasing genes in all species/regions
bp.df <- read.csv(file = "../cache/dev_expr_species/species_region_bp.csv", 
                  stringsAsFactors = FALSE)  # SI Table 11 subset
bp.df$bpmin <- mapply(ConvertPcdtoEventScore, log2(bp.df$bp..pcd. - 
                                                     1.96 * bp.df$bpse), 
                      bp.df$species)
bp.df$bpmax <- mapply(ConvertPcdtoEventScore, log2(bp.df$bp..pcd. + 
                                                     1.96 * bp.df$bpse), 
                      bp.df$species)
bp.subset <- subset(bp.df, species %in% c("macaque", "human")) # & region == "ACG")
bp.escore <- dcast(bp.subset, region + gene ~ species, value.var = "bp..event.score.")
bp.min <- dcast(bp.subset, region + gene ~ species, value.var = "bpmin")
bp.max <- dcast(bp.subset, region + gene ~ species, value.var = "bpmax")
bp.diff <- data.frame(bp.escore, bp.min[, 3:4], bp.max[, 3:4],
                      h_m_escore = bp.escore$human - bp.escore$macaque,
                      hmin_mmax = bp.min$human - bp.max$macaque,
                      hmax_mmin = bp.max$human - bp.min$macaque)

bp.diff$sig <- apply(bp.diff, 1, function(x) (as.numeric(x["h_m_escore"]) > 0 & 
                                                min(as.numeric(x[c("hmin_mmax", "hmax_mmin")])) > 0) | 
                       (as.numeric(x["h_m_escore"]) < 0 & 
                          max(as.numeric(x[c("hmin_mmax", "hmax_mmin")])) < 0))

# Summarize genes that have significantly different breakpoints
# between human and macaque based on event scores
# with(subset(bp.diff, sig == TRUE),
#      table(gene, region, h_m_escore < 0))

diff.summary <- data.frame()
# Human early
for (region1 in unique(bp.subset$region)) {
  genes <- subset(bp.diff, region == region1 & sig == TRUE & h_m_escore < 0)$gene
  diff1 <- with(subset(bp.subset, region == region1 & species == "human" & gene %in% genes),
                data.frame(set = "human_early", region1,  
                           Plateau = sum(! slope2sig), 
                           Decreasing = sum(slope2sig & slope2 < 0), 
                           Increasing = sum(slope2sig & slope2 > 0)))
  diff.summary <- rbind(diff.summary, diff1)
}

# Human late
for (region1 in unique(bp.subset$region)) {
  genes <- subset(bp.diff, region == region1 & sig == TRUE & h_m_escore > 0)$gene
  diff1 <- with(subset(bp.subset, region == region1 & species == "human" & gene %in% genes),
                data.frame(set = "human_late", region1,  
                           Plateau = sum(! slope2sig), 
                           Decreasing = sum(slope2sig & slope2 < 0), 
                           Increasing = sum(slope2sig & slope2 > 0)))
  diff.summary <- rbind(diff.summary, diff1)
}

diff.summaryl <- melt(diff.summary, id = c("set", "region1"))
colnames(diff.summaryl)[3:4] <- c("slope_after_breakpoint", "num_genes")
num.genes <- diff.summaryl[diff.summaryl$set == "human_early", "num_genes"] 
diff.summaryl[diff.summaryl$set == "human_early", "num_genes"] <- -num.genes

diff.summaryl$region1 <- factor(diff.summaryl$region1, 
                                levels = c("STR", "AM", "HP", "V1", "ACG"))

ggplot(diff.summaryl, aes(x = region1, y = num_genes, fill = slope_after_breakpoint)) + 
  facet_wrap(~ set) + 
  geom_bar(stat = "identity", width = 0.7) + 
  scale_fill_manual(values = c("grey", "blue", "red")) +
  coord_flip() +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylab("Number of genes") +
  xlab("Brain region")
```

# Calculate correlations with mouse
```{r compare-mouse-expr, fig.width=6, fig.height=6, warning=FALSE}
# Load mouse dev data
fn1 <- "../lib/mouse/devmouse_brainspan.csv"
dev.mouse <- read.csv(file=fn1)

# Convert age to factor
dev.mouse$age <- factor(dev.mouse$age, 
                        levels=c("E13.5", "E15.5", "E18.5", "P4", "P14", "P28"))

# Add mouse numeric ages (18.5 days gestation)
mouse.ages <- log2(c(13.5, 15.5, 18.5, 22.5, 32.5, 46.5))
names(mouse.ages) <- levels(dev.mouse$age)
dev.mouse$log2pcd <- round(mouse.ages[dev.mouse$age], 2)

# Calc expr zscores
keep.cols <- c("log2pcd", "gene_acronym", "DPall")
keep.ortho <- which(dev.mouse$gene_acronym %in% 
                      probes$mouse_genesymbol[probes$human_genesymbol %in% 
                                                ortho.genes])
dev.mousew <- dcast(dev.mouse[keep.ortho, keep.cols], gene_acronym ~ log2pcd, 
                    value.var="DPall")
rownames(dev.mousew) <- probes$human_genesymbol[match(dev.mousew$gene_acronym, probes$mouse_genesymbol)]
dev.mouse.expr <- dev.mousew[, -1]
dev.mouse.exprz <- t(apply(dev.mouse.expr, 1, scale))
colnames(dev.mouse.exprz) <- colnames(dev.mouse.expr)

dev.mouse.expr2 <- data.frame(species="mouse", melt(as.matrix(dev.mouse.expr)), 
                              exprz=melt(dev.mouse.exprz)$value)
colnames(dev.mouse.expr2) <- colnames(dev.expr)[1:ncol(dev.mouse.expr2)]

# Add mouse escore ages
dev.mouse.expr2$escore <- round(sapply(dev.mouse.expr2$log2pcd, 
                                       ConvertPcdtoEventScore, "mouse"), 2)

# Combine mouse data with human/macaque/rat
dev.expr2 <- rbind(dev.expr, dev.mouse.expr2)
dev.expr2$species <- factor(dev.expr2$species, levels = c("human", "macaque", 
                                                          "rat", "mouse"))
```

```{r fit-dev-trend-mouse, eval=TRUE}
dev.pred.fn <- "../cache/dev_expr_species/dev.expr_dev.pred_mouse.RData"

# Try loading cached fits
rm(dev.pred)
# try(load(dev.pred.fn), silent=TRUE)

# SLOW - Run only as needed
if (! exists("dev.pred")) {
  
  # Keep genes with data from all species
  gene.cnt <- table(dev.expr2$gene)
  keep.ortho.genes <- names(gene.cnt)[gene.cnt == max(gene.cnt)]
  dev.expr3 <- droplevels(subset(dev.expr2, gene %in% keep.ortho.genes))
  
  # Calc Translating Time escore
  dev.expr3$escore <- apply(dev.expr3, 1, 
                            function(x) ConvertPcdtoEventScore(as.numeric(x["log2pcd"]), 
                                                               x["species"]))
  dev.expr3$escore <- round(dev.expr3$escore, 2)
  
  # Calc spline fit
  # Select escores that are near all 3 species
  escore1 <- c(0.27, 0.36, 0.46, 0.54, 0.75, 0.85, 0.96, 1.32)
  dev.pred <- list()
  for (species1 in c("macaque", "human", "rat", "mouse")) {
    species.dev <- subset(dev.expr3, species==species1)
    pred.df <- NULL
    for (gene1 in keep.ortho.genes) {
      # Select rows corresponding to each gene
      gene.dev <- subset(species.dev, gene == gene1)
      
      # Fit expr trend
      gene.lo <- loess(expr ~ escore, gene.dev, degree=1)
      expr.pred <- predict(gene.lo, data.frame(escore = escore1))
      pred.df <- rbind(pred.df, expr.pred)
    }
    rownames(pred.df) <- keep.ortho.genes
    dev.pred[[species1]] <- pred.df
  }
  
  # Save expr fits
  save(dev.expr3, dev.pred, file=dev.pred.fn)
}
```


```{r calc-species-cor-mouse, eval=TRUE}
# Genes to keep
gene.cnt <- table(dev.expr3$gene)
keep.ortho.genes <- names(gene.cnt)[gene.cnt == max(gene.cnt)]

# Calc species expr correlation
cor.method <- "spearman"
cor.all <- NULL
pval.all <- NULL
for (gene1 in keep.ortho.genes) {
  cor1 <- cor.test(dev.pred[["mouse"]][gene1, ], dev.pred[["human"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor2 <- cor.test(dev.pred[["macaque"]][gene1, ], dev.pred[["mouse"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor3 <- cor.test(dev.pred[["mouse"]][gene1, ], dev.pred[["rat"]][gene1, ], 
                   method=cor.method, alternative="two.sided")
  cor.all <- rbind(cor.all, c(cor1$est, cor2$est, cor3$est))
  pval.all <- rbind(pval.all, c(cor1$p.val, cor2$p.val, cor3$p.val))
}
rownames(cor.all) <- keep.ortho.genes
colnames(cor.all) <- paste(c("mouse-human", "macaque-mouse", "mouse-rat"), 
                           "r", sep = "_")
rownames(pval.all) <- keep.ortho.genes
colnames(pval.all) <- paste(c("mouse-human", "macaque-mouse", "mouse-rat"), 
                           "pval", sep = "_")

# Save correlations
write.csv(data.frame(cor.all, pval.all), file="../cache/dev_expr_species/devcor_mouse.csv")

```