---
output: 
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
# knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```


```{r init-workspace, echo=FALSE, message=FALSE, warning=FALSE}
options(stringsAsFactors = FALSE)

# Load libraries
library(reshape2)
library(dplyr)
library(relaimpo)
library(limma)
library(pheatmap)
library(fpc)
library(ggplot2)
library(gtools)
library(beanplot)
library(RColorBrewer)

# Load functions
source(file="../src/fFindSampleSubsets.R")
source(file="../src/fReorderFactorLevels.R")
source(file="../src/fCalcGoEnrich.R")

```

```{r load-data, echo=FALSE}
# Load starting data: expr, samples, and probes
load(file="../cache/nhp_PrePost_StartingData.RData")

```


```{r calc-laminar-gene-var, eval=FALSE}
# Calc laminar spatial enrichment (L1-WM only, L2/3, L4 combined)
struc.name <- "NCX_Ocx_V1"

# Combine MZ/L1, IZ/WM
samplePrePost$layer_dev <- sub("MZ", "L1", samplePrePost$layer_dev)
samplePrePost$layer_dev <- sub("IZ", "WM", samplePrePost$layer_dev)
samplePrePost$layer_dev[samplePrePost$layer_dev == "L2"] <- "L2_3"
samplePrePost$layer_dev[samplePrePost$layer_dev == "L3"] <- "L2_3"

# Select groups of samples (V1 L1-WM)
struc.subset <- with(samplePrePost, 
                     which(subregion == "V1" &
                             layer_dev %in% c("L1", "L2_3", "L4", 
                                              "L5", "L6", "WM") & 
                       ! age %in% c("E40", "E50", "E70")))
exprPrePost.subset <- exprPrePost[, struc.subset]
samplePrePost.subset <- droplevels(samplePrePost[struc.subset, ])

# Collapse layers to have one sample per age/donor/layer
struc.label <- with(samplePrePost.subset, paste(age, layer_dev, donor_name, 
                    sep="_"))

# Tranpose expr df to use aggregate fnc
exprPrePost.subset2 <- as.data.frame(t(exprPrePost.subset))
exprPrePost.subset2$label <- struc.label

# Calc mean expr by donor/layer
exprPrePost.subset3 <- aggregate(. ~ label, data=exprPrePost.subset2, FUN=mean)

# Remove label column and transpose
exprPrePost.subset4 <- t(exprPrePost.subset3[, -1])

# NOTE: sample info no longer accurate for collapsed layers
struc.order <- match(exprPrePost.subset3$label, struc.label)  # First match

# Reorder sample info df to match expr df
samplePrePost.subset2 <- droplevels(samplePrePost.subset[struc.order, ])


# Perform independent laminar analysis of each sample group
laminar.enrichment.all <- vector("list", nlevels(samplePrePost.subset2$age))
names(laminar.enrichment.all) <- levels(samplePrePost.subset2$age)

for (timepoint in levels(samplePrePost.subset2$age)) {
  print(timepoint)  # Keep track of progress
  age.subset <- which(samplePrePost.subset2$age == timepoint)
  coef1 <- data.frame()
  for (gene in probes$macaque_genesymbol[1:10]) {
    gene.subset <- which(probes$macaque_genesymbol == gene)
    expr1 <- exprPrePost.subset4[gene.subset, age.subset]
    expr1.scaled <- scale(expr1)
    
    layer1 <- factor(samplePrePost.subset2$layer_dev[age.subset])
    layer1.levels <- levels(layer1)
    layer1.num <- length(layer1.levels)
    
    # Create effects contrast formula (grand mean deviation coding)
    lm1.vi.all <- matrix(NA, layer1.num, layer1.num)
    
    # Due to multi-collinearity of templates, leave each template out
    for (contr.layer in 1:layer1.num) {
      p1 <- paste0("layer_dev == '", layer1.levels[-contr.layer], "'")
      p2 <- paste0("layer_dev == '", layer1.levels[contr.layer], "'")
      p3 <- paste0("scale(I((", p1, ") - (", p2, ")))")
      p4 <- paste(p3, collapse = " + ")
      
      contr.layer.formula <- as.formula(paste0("expr1.scaled ~ ", p4))
      lm1 <- lm(contr.layer.formula, 
                data = samplePrePost.subset2[age.subset, ])
      
      # Estimate proportion of variance explained by each structure
      # lmg method preferred but slower than car transformation (cf Bi 2012)
      lm1.vi <- calc.relimp(lm1, type = "car", rela = TRUE)
      lm1.R2 <- lm1.vi$R2
      lm1.vi.sign <- lm1.vi$car * sign(summary(lm1)$coef[-c(1), "Estimate"])
      lm1.vi.all[-contr.layer, contr.layer] <- lm1.vi.sign
    }
    # Find average variable importance across sets of templates
    lm1.vi.mean <- apply(lm1.vi.all, 1, mean, na.rm=TRUE)
    lm1.vi.r2 <- lm1.vi.mean / sum(abs(lm1.vi.mean)) * lm1.R2
    
    # Clean up layer names
    names(lm1.vi.r2) <- layer1.levels
    coef1 <- rbind(coef1, data.frame(timepoint, gene, lm1.R2, t(lm1.vi.r2)))
  }
  laminar.enrichment.all[[timepoint]] <- coef1
}

# Update rownames with gene symbols
for (timepoint in levels(samplePrePost.subset2$age)) { 
  rownames(laminar.enrichment.all[[timepoint]]) <- 
    laminar.enrichment.all[[timepoint]]$gene
}

# Save laminar enrichment data ####
laminar.folder <- "../cache/laminar_genes/"
laminar.file <- paste0("laminar.enrichment.all_", struc.name, "_L1-WM_dev.RData")
# save(laminar.enrichment.all, file = paste0(laminar.folder, laminar.file))

```


```{r calc-laminar-dex, eval=FALSE}
ages <- levels(samplePrePost.subset2$age)
kNumTests <- length(ages)
keep.samples.list <- vector("list", kNumTests)
groups.list <- vector("list", kNumTests)

# Define comparisons
sig.tests <- ages
sig.list <- vector("list", kNumTests)
names(sig.list) <- sig.tests

for (i in 1:length(ages)) {
  keep.samples <- which(samplePrePost.subset2$age == ages[i])
  keep.samples.list[[i]] <- keep.samples
  sample.subset <- droplevels(samplePrePost.subset2[keep.samples, ])
  groups.list[[i]] <- factor(sample.subset$layer_dev, levels = )
}

# ANOVA for predefined tests
for (i in 1:kNumTests) {
  keep.samples <- keep.samples.list[[i]]
  groups <- groups.list[[i]]
  
  expr.subset <- exprPrePost.subset4[, keep.samples]
  
  # LIMMA - DEX analysis
  design <- model.matrix(~ 0 + groups)
  colnames(design) <- levels(groups)
  fit <- lmFit(expr.subset, design)
  
  # Define contrast matrix (each group vs. others)
  contr.groups <- paste(levels(groups), "fc", sig.tests[i], sep = "_")
  contr.dev <- diag(nlevels(groups))
  contr.dev[lower.tri(contr.dev)] <- -1 / (nlevels(groups) - 1)
  contr.dev[upper.tri(contr.dev)] <- -1 / (nlevels(groups) - 1)
  rownames(contr.dev) <- levels(groups)
  colnames(contr.dev) <- contr.groups

  # Rank DEX
  fit2 <- eBayes(contrasts.fit(fit, contr.dev))
  dex.table <- topTable(fit2, number = Inf, adjust = "BH", sort.by = "none")
  
  # Remove FC calc for non-sig tests
  dex.table[dex.table$adj.P.Val >= 0.05, contr.groups] <- NA  # Check signif
  sig <- dex.table[, contr.groups]
  
  # Store sig (convert to fold-change)
  sig.list[[i]] <- 2^sig
}

# Create data frame of DEX sigs
sig.df <- do.call(cbind, sig.list)

# Save table of laminar DEX genes
# write.csv(sig.df, file = "../analysis/laminar_genes/sig.df_L1-WM_dev.csv", 
#           row.names = FALSE)

```


```{r save-laminar-gene-lists, eval=FALSE}
#  Find V1 laminar genes by age/layer (L1-WM only, L4 combined)

# Pick structure for analysis
struc.name <- "NCX_Ocx_V1"
laminar.folder <- "../cache/laminar_genes/"
laminar.summary.all <- data.frame()

# Load laminar enrichment information for structure
laminar.file <- paste0("laminar.enrichment.all_", struc.name, "_L1-WM_dev.RData")
load(file = paste0(laminar.folder, laminar.file))

# Find laminar genes for each age and layer
for (age1 in names(laminar.enrichment.all)) {
  # Laminar R^2 subset
  laminar.enrichment <- laminar.enrichment.all[[age1]]
  layer.col <- ! colnames(laminar.enrichment) %in% 
    c("timepoint", "gene", "lm1.R2", "toplevel")
  layer.R2 <- laminar.enrichment[, layer.col]
  
  # Laminar DEX subset
  age.col <- grep(age1, colnames(sig.df))
  sig.df.subset <- sig.df[, age.col]
  
  # For each gene, find partial R^2 of 2nd most enriched layer
  penult.layer.R2 <- apply(layer.R2, 1, function(x) x[order(-x)[2]])
  
  # Find laminar enriched and specific genes
  enriched.threshold <- 0.25
  specific.threshold <- 0.1
  fc.thresh <- 1.5
  for (layer1 in colnames(layer.R2)) {
    layer1.col <- which(colnames(layer.R2) == layer1)
    gene.index <- which(layer.R2[, layer1] > enriched.threshold & 
                          sig.df.subset[, layer1.col] > fc.thresh)
    laminar.enriched.genes <- laminar.enrichment$gene[gene.index]
    laminar.enriched <- gene.index > 0
    
    # Gene is specific to layer if no other layer explains more than
    # threshold of variance
    laminar.specific <- abs(penult.layer.R2[gene.index]) < specific.threshold
    
    # Keep same number of columns if no laminar genes
    if (length(gene.index) == 0) {
      laminar.enriched.genes <- NA
      laminar.enriched <- NA
      laminar.specific <- NA
    }
    
    # Create table summary of laminar genes
    laminar.summary <- data.frame(region = struc.name, age1, layer1, 
                                  gene = laminar.enriched.genes,
                                  enriched = laminar.enriched, 
                                  specific = laminar.specific)
    laminar.summary.all <- rbind(laminar.summary.all, laminar.summary)
  }
}

# Rename columns
colnames(laminar.summary.all) <- gsub("1", "", colnames(laminar.summary.all))

# Reorder age factor
age.order <- c("E80", "E90", "E120", "0M", "3M", "12M", "48M")
laminar.summary.all$age <- 
  ReorderFactorLevels(laminar.summary.all$age, 
                      level.order = age.order, 
                      ordered = TRUE)

# Add macaque Entrez ids
match.genes <- match(laminar.summary.all$gene, probes$macaque_genesymbol)
laminar.summary.all$geneid <- probes$macaque_entrezid[match.genes]

# Save table of laminar genes
# write.csv(laminar.summary.all, file = "../analysis/laminar_genes/laminar.summary.all_L1-WM_dev.csv", 
# row.names = FALSE)


# Get lists of genes that have maximal laminar enrichment
max.laminar.genes <- NULL
for (timepoint in names(laminar.enrichment.all)) {
  gene.list <- NULL
  layer.names <- colnames(laminar.enrichment.all[[timepoint]])
  layer.names <- layer.names[! layer.names %in% 
                               c("timepoint", "gene", "lm1.R2")]
  for (layer in layer.names) {
    order1 <- order(laminar.enrichment.all[[timepoint]][, layer], 
                    decreasing = TRUE)
    gene.list <- cbind(gene.list, 
                       laminar.enrichment.all[[timepoint]][, "gene"][order1])
  }
  colnames(gene.list) <- paste(timepoint, layer.names, sep = "_")
  max.laminar.genes <- cbind(max.laminar.genes, gene.list)
}

# write.table(max.laminar.genes, file = "../analysis/laminar_genes/V1(L1-WM)_max_laminar_genes_byage.txt", 
# quote = FALSE, row.names = FALSE, sep = "\t")

```


# Figure 4b
```{r calc-laminar-timing, fig.width=1.2, fig.height=3, eval=TRUE}
# Load table of laminar genes
laminar.summary.all <- read.csv(file = "../analysis/laminar_genes/laminar.summary.all_L1-WM_dev.csv")

# Reorder age factor
age.order <- c("E80", "E90", "E120", "0M", "3M", "12M", "48M")
laminar.summary.all$age <- 
  ReorderFactorLevels(laminar.summary.all$age, 
                      level.order = age.order, 
                      ordered = TRUE)

# KLUDGE - convert laminar matrix into format used in prior code
layers <- c("L2_3", "L4", "L5", "L6")
lam.summary.list <- list()
for (layer1 in layers) {
  lam.summary <- with(subset(laminar.summary.all, layer == layer1), 
                      table(gene, age))
  lam.summary.list[[layer1]] <- lam.summary
}


# Define vars
lam.marker.groups.list <- vector("list", 4)
names(lam.marker.groups.list) <- c("L2_3", "L4", "L5", "L6")
lam.lag.all <- matrix(ncol = 6, nrow = 4, 
                      dimnames=list(c("L2_3", "L4", "L5", "L6"), 
                                    c("E90", "E120", "0M", "3M", "12M", "48M")))

for (layer1 in c("L2_3", "L4", "L5", "L6")) {
  lam.summary <- lam.summary.list[[layer1]]
  
  # Remove genes that are laminar at only a single age
  lam.count <- apply(lam.summary, 1, sum)
  lam.summary.subset <- lam.summary[lam.count > 1, ]
  
  # Define timing based on median age of laminarity
  lam.marker.groups <- list()
  pan.lam <- which(apply(lam.summary.subset, 1, function(x) sum(x) >= 5))
  lam.marker.groups[["Pan"]] <- rownames(lam.summary.subset)[pan.lam]
  
  lam.summary.subset2 <- lam.summary.subset[-pan.lam, ]
  lam.age <- 1 / apply(lam.summary.subset2, 1, 
                       function(x) median(c(1 / c(80, 90, 120, 165, 255, 530, 1625))[x == 1]))
  lam.age2 <- apply(lam.summary.subset2, 1, mean)
  lam.age.order <- order(lam.age, lam.age2)
  lam.marker.groups[["Early"]] <- rownames(lam.summary.subset2)[which(lam.age < 120)]
  lam.marker.groups[["Middle"]] <- rownames(lam.summary.subset2)[which(lam.age >= 120 & 
                                                                        lam.age <= 255)]
  lam.marker.groups[["Late"]] <- rownames(lam.summary.subset2)[which(lam.age > 255)]
  
  # Plot laminar ages
  lam.summary.subset3 <- rbind(lam.summary.subset2[lam.age.order, ], 
                               lam.summary.subset[pan.lam, ])
  timing.names <- names(lam.marker.groups[c(2:4, 1)])
  timing.ngenes <- sapply(lam.marker.groups[c(2:4, 1)], length)
  
  # Annotate genes with timing set
  annot.row <- data.frame(Timing=factor(rep(timing.names, timing.ngenes)))
  rownames(annot.row) <- rownames(lam.summary.subset3)
  pal.row <- rev(brewer.pal(4, "Set1"))

  # Plot binary heatmap
  pheatmap(lam.summary.subset3, 
           cluster_rows = FALSE, cluster_cols = FALSE, legend=FALSE, 
           annotation_row=annot.row, annotation_legend=FALSE, 
           annotation_colors=list(Timing= c(Early=pal.row[1], Middle=pal.row[2], 
                                            Late=pal.row[3], Pan=pal.row[4])), 
           color=c("white", "black"), show_rownames = FALSE, main=layer1)

  # Store layer age counts
  lam.marker.groups.list[[layer1]] <- lam.marker.groups
  
  # Add number of genes to group names
  names(lam.marker.groups) <- paste(names(lam.marker.groups), 
                                    sapply(lam.marker.groups, length))
  
}

```


```{r calc-laminar-go-enrich, eval=FALSE}
lam.groups <- c("Pan", "Early", "Middle", "Late")
lam.go.list <- list()

for (group1 in lam.groups) {
  # Select Human entrez ids for laminar group
  lam.genes <- c(lam.marker.groups.list[["L2_3"]][[group1]], 
                 lam.marker.groups.list[["L4"]][[group1]], 
                 lam.marker.groups.list[["L5"]][[group1]], 
                 lam.marker.groups.list[["L6"]][[group1]])
  lam.ids <- probes$human_entrezid[match(lam.genes, probes$macaque_genesymbol)]
  lam.ids <- na.omit(unique(lam.ids))
  
  # Calc GO enrichment
  lam.go.list[[group1]] <- CalcGoEnrich(lam.ids, cond=FALSE)
}

lam.go.df <- do.call(rbind, lam.go.list)
lam.go.df$Set <- sub("[.][0-9]*", "", rownames(lam.go.df))

# write.csv(lam.go.df, file="../analysis/laminar_genes/lam.go.df_L1-WM_dev.csv", 
#           row.names=FALSE)

```


```{r plot-laminar-go-enrich, fig.width=7, fig.height=3.5, eval=FALSE}
# Load GO terms
lam.go.df <- read.csv(file="../analysis/laminar_genes/lam.go.df_L1-WM_dev.csv")

# Select GO terms to plot
keep.go <- subset(lam.go.df, Pvalue < 1e-4 & Count >= 5 & Size < 500)$Term

lam.go.dfw <- dcast(lam.go.df[, c("Set", "Term", "Pvalue")], 
                    Term ~ Set, value.var="Pvalue")
lam.go.dfw <- subset(lam.go.dfw, Term %in% keep.go)
rownames(lam.go.dfw) <- lam.go.dfw$Term
lam.go.dfw <- lam.go.dfw[, c("Early", "Middle", "Late", "Pan")] 
lam.go.dfw[is.na(lam.go.dfw)] <- 1
lam.go.dfw <- -log10(lam.go.dfw)

# Order terms by age of GO enrichment
lam.go.age <- apply(lam.go.dfw, 1, 
                    function(x) median(c(1:ncol(lam.go.dfw))[x > 4]))
lam.order <- order(lam.go.age)

# Minor manual reordering
lam.order <- lam.order[c(1:5, 7:14, 6, 15:length(lam.order))]

# Plot heatmap of GO Term enrichment
pheatmap(lam.go.dfw[lam.order, ], border=NA, 
         cluster_rows=FALSE, cluster_cols=FALSE)

```
