---
output: 
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
# knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```

```{r init-workspace}
options(StringsAsFactors = FALSE)

# Load libraries
library(reshape2)
library(MASS)
library(pheatmap)
library(RColorBrewer)
library(ggplot2)

# Load functions
source('../src/fCalcGoEnrich.R')

# Load GO term db
if (! exists("xx")) {
  xx <- as.list(GOTERM)
  xx <- xx[!is.na(xx)]
}
if (! exists("yy")) {
  yy <- as.list(GOBPOFFSPRING)
  yy <- yy[!is.na(yy)]
}

```


```{r calc-go-matrix, eval=FALSE}
# Load matrix of max changing genes
# Use "all" to calculate GO enrichment for all samples (SLOW)
# Use "toplevel" to calculate GO enrichment for major regions
region.subset <- "toplevel"  #  all  toplevel
try(max.change.genes <- read.table(file = paste0("../cache/expr_dynamics/max.change.genes_", 
                                                 region.subset, ".txt"), header=TRUE))

# Load perm scores
try(load(file = "../cache/expr_dynamics/perm/gene.list.overlap.summary_random_all.RData"))

# Create lists of significantly overlapping genes
kRateDir <- c("decreasing", "increasing")

for (onto1 in c("BP")) {  # , "CC", "MF"
  # Init data frames
  go.sig.all <- data.frame()
  gene.intersect.all <- data.frame()
  for (rate.dir in kRateDir) {
#   rate.dir <- kRateDir[1]
    # Create filter for significant gene list overlap
    try(load(file = paste0("../cache/expr_dynamics/gene.list.overlap.summary_", 
                     region.subset, "_", rate.dir, ".RData")))
    score.matrix <- gene.list.overlap.summary[["score"]]
    # Set signficant score threshold (FWER < p.thresh)
    num.tests <- sum(lower.tri(score.matrix))
    p.thresh <- 0.025  # Increasing and decreasing gene comparisons
    score.cutoff <- quantile(all.perm.scores, 1 - (p.thresh / num.tests))
    keep.overlap <- score.matrix > score.cutoff
    keep.overlap <- upper.tri(keep.overlap) & keep.overlap
    diag(keep.overlap) <- TRUE
    
    # Compare only top n ranked genes
    top.n <- 1000
    if (rate.dir == "increasing") {
      keep.genes <- 1:top.n
    } else {
      keep.genes <- nrow(max.change.genes):(nrow(max.change.genes) - top.n + 1)
    }
    max_genes <- max.change.genes[keep.genes, ]
    
    # GO enrichment by region
    # kStart <- c(131, 191, 221, 251, 281, 331)
    # kEnd <- c(190, 220, 250, 280, 330, 419)
    kStart <- 1
    kEnd <- ncol(max_genes)
    set1 <- 1
    for (region1 in kStart[set1]:kEnd[set1]) { # 1:ncol(max_genes)
      # Print script progress
      print(region1)
      for (region2 in region1:ncol(max_genes)) {
        if (keep.overlap[region1, region2] == TRUE) {
          intersect1 <- intersect(max_genes[, region1], max_genes[, region2])
          go1 <- CalcGoEnrich(intersect1, id.type="gene_symbol", hgCutoff = 0.05, 
                              onto = onto1, cond = FALSE)
        } else {
          intersect1 <- NA
          names(intersect1) <- "intersect1"
          go1 <- NA
          names(go1) <- "go1"
        }

        # Store results
        gene.intersect <- data.frame(dir = rate.dir, 
                                     i = colnames(max_genes)[region1],
                                     j = colnames(max_genes)[region2], 
                                     gene = intersect1)
        gene.intersect.all <- rbind(gene.intersect.all, gene.intersect)
        
        go.sig <- data.frame(dir = rate.dir, 
                             i = colnames(max_genes)[region1],
                             j = colnames(max_genes)[region2], 
                             onto = onto1, GOid = names(go1), p = go1)
        go.sig.all <- rbind(go.sig.all, go.sig)
      }
    }
  }
  # Save results
  fn1 <- paste0("../analysis/go_enrich/", region.subset, 
                "_", kStart[set1], "_", kEnd[set1], "_", onto1, ".Rdata")
  save(gene.intersect.all, go.sig.all, file=fn1)
}

```


```{r go-term-clustering, eval=FALSE}
# Load GO enrichment
if (! exists("go.sig.all")) {
  kOnto <- "BP"
  kRegion <- "toplevel"  # toplevel
  load(file = paste0("../analysis/go_enrich/", kRegion, "_", kOnto, ".Rdata"), 
       verbose = TRUE)
  
  # Keep nominally significant GO terms
  go.sig.all <- subset(go.sig.all, grepl("GO:", GOid) & p < 0.05)
  go.sig.all <- na.omit(go.sig.all)
  
  # Convert p-values to -log10
  go.sig.all$p <- -log10(go.sig.all$p)
}

# Convert list to GOid x Region wide matrix
go.sig.allw <- dcast(go.sig.all, GOid ~ dir + i + j, value.var = "p")
# Label with GO terms
rownames(go.sig.allw) <- go.sig.allw$GOid
# Remove GO term column
go.sig.allw <- go.sig.allw[, -match("GOid", colnames(go.sig.allw))]
# Assign pval = 0 to unassociated GO terms
go.sig.allw[is.na(go.sig.allw)] <- 0


```


```{r analyze-go-trends, eval=FALSE}
# Load increasing or decreasing gene overlap matrix
region.subset <- "toplevel"  # all  toplevel
load(file=paste0("../cache/go_enrich/m.template_", region.subset, ".RData"))
m.dim <- ncol(m.template)

# Threshold p-values
go.sig.allw.subset <- go.sig.allw
p.thresh <- -log10(0.01)  # B-H 0.001 ~ nom 0.05?
go.sig.allw.subset[go.sig.allw.subset <= p.thresh] <- 0  # Not signif
go.sig.allw.subset[go.sig.allw.subset > p.thresh] <- 1  # Signif

# Remove regions with no significant GO terms
sig.regions <- apply(go.sig.allw.subset, 2, function(x) any(x > 0))
go.sig.allw.subset <- go.sig.allw.subset[, sig.regions]

# Most common GO terms (incr / decr)

kRateDir <- c("increasing", "decreasing")
top.goid <- vector("list", length(kRateDir))
names(top.goid) <- kRateDir
# kTopN <- 1000

for (dir1 in kRateDir) {
  # Check all GO ids associated with at least 10 regions / ages
  kTopN <- max(which(sort(apply(go.sig.allw.subset[, grep(dir1, colnames(go.sig.allw.subset))], 1, sum), decreasing = TRUE) == 10))
  top.goid[[dir1]] <- sapply(names(sort(apply(go.sig.allw.subset[, grep(dir1, colnames(go.sig.allw.subset))], 1, sum), decreasing = TRUE))[1:kTopN], function(goid) if(goid %in% names(xx)) slot(xx[[goid]], "GOID"))
}


##########
# Check which regions are associated with GO term + offspring

# Load clustered order based on gene list overlap
fn1 <- paste0("../analysis/go_enrich/", 
              region.subset, "/clust.order.lab.txt")
clust.order.lab <- scan("character", file=fn1)  
row.order <- match(clust.order.lab, colnames(m.template))

# Region/age cols
regions <- c("NCX", "HP", "AM", "BG", "TH")
ages <- c("E50", "E70", "E80", "E90", "E120", "0M", "3M", "12M", "48M")
region.age.col <- sapply(regions, function(x) sapply(ages, function(y) intersect(grep(x, colnames(m.template)[row.order]), grep(y, colnames(m.template)[row.order]))))
names(region.age.col) <- paste0(rep(regions, each=9), "_", ages)
# Remove region/age combinations without data
region.age.col <- region.age.col[sapply(region.age.col, length) > 0]

# Init vars
go.overlap.all <- list()  # Save GO overlap matrices

# Select GO id to check for enrichment
for (top.dir1 in kRateDir) {
#   top.dir1 <- "decreasing"  # Test single direction
  go.rank <- 0
  for (id1 in top.goid[[top.dir1]]) {
#     id1 <- "GO:0035930"  # Test single term
    # Rank of GO term
    go.rank <- go.rank + 1
    
    # Select GO terms
    goid <- id1
    goid <- c(goid, yy[[goid]])  # Offspring
    goid <- goid[goid %in% rownames(go.sig.allw.subset)]
    goid.name <- paste0(id1, " ", slot(xx[[id1]], "Term"), 
                        " (", length(goid), ")")
    sig.goid <- sort(apply(go.sig.allw.subset[goid, apply(go.sig.allw.subset[goid, ], 2, 
                                            function(x) sum(x > 0) > 0)], 2, sum))
    xy <- cbind(sig.goid, sig.goid)
    xy <- xy / length(goid)  # Normalize by number of GO terms in subtree
    xy.lab <- rownames(xy)

    # Check if variability in GO term enrichment
    if (length(table(xy)) > 2) {
      
      # Plot GO strength as ordered heatmap
      go.overlap.dir <- vector("list", length(kRateDir))
      names(go.overlap.dir) <- kRateDir
      
      for (dir1 in kRateDir) {
        dir.subset <- grep(dir1, xy.lab)
        if (length(dir.subset) > 1) {
          xy.subset <- xy[dir.subset, ]
          xy.lab.subset <- xy.lab[dir.subset]
          xy.lab.subset <- sub("^.*creasing_", "", xy.lab.subset)
          # Split labels into two regions comparedg
          xy.lab.list <- strsplit(xy.lab.subset, "_")
          xy.split <- t(sapply(xy.lab.list, 
                               function(x) c(paste(x[1:min(which(x %in% ages))], 
                                                   collapse="_"), 
                                             paste(x[(min(which(x %in% ages)) + 1):length(x)], 
                                                   collapse="_"))))
          
          # Overlap heatmap template
          go.overlap <- matrix(0, m.dim, m.dim, dimnames = list(rownames(m.template), 
                                                           colnames(m.template)))
          for (i in 1:nrow(xy.split)) {
            go.overlap[xy.split[i, 1], xy.split[i, 2]] <- xy.subset[i, 1]
            go.overlap[xy.split[i, 2], xy.split[i, 1]] <- xy.subset[i, 1]
          }
          
          go.overlap2 <- go.overlap[row.order, row.order]
          go.overlap.dir[[dir1]] <- go.overlap2
        }
      }
      
      go.overlap.combined <- matrix(0, m.dim, m.dim)
      if (!is.null(go.overlap.dir[["increasing"]])) {
        go.overlap.combined <- upper.tri(go.overlap.dir[["increasing"]]) * 
          go.overlap.dir[["increasing"]]
      }
      if (!is.null(go.overlap.dir[["decreasing"]])) {
        go.overlap.combined <- go.overlap.combined + 
          lower.tri(go.overlap.dir[["decreasing"]]) * go.overlap.dir[["decreasing"]]
      }
      # Diagonal should represent data from current rate direction
      diag(go.overlap.combined) <- diag(go.overlap.dir[[top.dir1]])
      
#       go.overlap.combined[go.overlap.combined == 0] <- NA  # Need for log10 scale
  
      # Check if variability in GO term enrichment
      if (length(table(go.overlap.combined)) > 1) {
        # Save GO overlap matrix
        go.overlap.all[[top.dir1]][[id1]] <- go.overlap.combined
        
        # Save all heatmaps?
        kPlot <- FALSE
        
        if (kPlot == TRUE) {
          # Plot heatmap
          pal1 <- colorRampPalette(c("white", brewer.pal(n = 9, name = "YlOrRd")), 
                               space = "rgb")(100) 
          
          goid.fn <- sub("/", "~", sub(":", "~", goid.name))
          # Shorten filename to fit Windows max 260 char (path + fn)
          if (nchar(goid.fn) > 100) goid.fn <- substr(goid.fn, 1, 100)
          fn.plot <- paste0("../analysis/go_enrich/", region.subset, "/goid/", 
                            kOnto, "/", top.dir1, "_", 
                            sprintf("%04d", go.rank), kOnto, "_", 
                            goid.fn, ".png")
          png(width=5000, height=5000, file = fn.plot)  # High res for all structures
            pheatmap(go.overlap.combined, cluster_rows = FALSE, 
                     cluster_cols = FALSE, border = NA, color = pal1, 
                     main = goid.name)
          dev.off()
        }
      }
    }
  }
}

fn1 <- paste0("../analysis/go_enrich/go.overlap.all_", 
              region.subset, "_BP.Rdata")
# save(go.overlap.all, file=fn1)

```


```{r go-overlap-analysis, eval=FALSE}
# Define functions
GoDiff <- function(go.heatmap, col1, dir1, return.val = "p") {
  go.prop <- data.frame()
  for (y in col1) {
    if (dir1 == "increasing") {
      go.prop <- rbind(go.prop, cbind(colnames(go.heatmap)[y], 
                                      c(go.heatmap[y, y:m.dim], 
                                        go.heatmap[1:(y-1), y])))
    } else {
      go.prop <- rbind(go.prop, cbind(colnames(go.heatmap)[y], 
                                      c(go.heatmap[y:m.dim, y], 
                                        go.heatmap[y, 1:(y-1)])))      
    }
  }
  go.prop[, 2] <- as.numeric(as.character(go.prop[, 2]))
  colnames(go.prop) <- c("struc.age", "go.prop")
  aov1 <- aov(go.prop ~ struc.age, go.prop)
  aov.p <- summary(aov1)[[1]][1, 5]
  if (return.val == "p") {
    # Return ANOVA p-value
    return(aov.p)
  } else {
    # Return significant pairwise comparisons
    pw.df <- TukeyHSD(aov1)$struc.age
    pw.sign <- sign(pw.df[, 1])
    pw.id.list <- strsplit(rownames(pw.df), "-")
    pw.id.all <- NULL
    for (i in 1:length(pw.sign)) {
      if(pw.sign[i] == 1) {
        pw.id <- paste(c(pw.id.list[[i]][1], pw.id.list[[i]][2]), 
                       collapse = "-")
      } else {
        # Reverse name so region with greater expr is first
        pw.id <- paste(c(pw.id.list[[i]][2], pw.id.list[[i]][1]), 
                       collapse = "-")
      }
        pw.id.all <- c(pw.id.all, pw.id)
    }
    
    pw.sig.id <- paste(pw.id.all[pw.df[, "p adj"] < 0.05], collapse = "; ")
    return(pw.sig.id)
  }
}

# T-test of 2 regions
GoCompareRegions <- function(go.heatmap, col1, dir1) {
  go.prop <- data.frame()
  for (y in col1) {
    if (dir1 == "increasing") {
      region.name <- ifelse(y %in% col1[1:2], "ctx", "subctx")
      go.prop <- rbind(go.prop, cbind(region.name, 
                                      c(go.heatmap[y, y:m.dim], 
                                        go.heatmap[1:(y-1), y])))
    } else {
      region.name <- ifelse(y %in% col1[1:2], "ctx", "subctx")
      go.prop <- rbind(go.prop, cbind(region.name, 
                                      c(go.heatmap[y:m.dim, y], 
                                        go.heatmap[y, 1:(y-1)])))      
    }
  }
  go.prop[, 2] <- as.numeric(as.character(go.prop[, 2]))
  colnames(go.prop) <- c("struc.age", "go.prop")
  t1 <- t.test(go.prop ~ struc.age, go.prop)
  if (t1$p.val < 0.05) {
    if (sign(t1$stat) == 1) {
      region1 <- "ctx"
    } else {
      region1 <- "subctx"
    }
  } else {
    region1 <- "mixed"
  }
  return(region1)
}


# Calc mean GO enrichment by region / age
go.spec.all <- NULL
if (top.dir1 == "decreasing") {
  go.spec1 <- sapply(region.age.col, 
                     function(x) mean(sapply(x, 
                      function(y) mean(c(go.overlap.combined[y:m.dim, y], 
                                         go.overlap.combined[y, 1:(y-1)]), 
                                       na.rm = TRUE))))
} else {
  go.spec1 <- sapply(region.age.col,
                     function(x) mean(sapply(x, 
                      function(y) mean(c(go.overlap.combined[y, y:m.dim],
                                         go.overlap.combined[1:(y-1), y]), 
                                       na.rm = TRUE))))
}

# Combine results
go.spec.all <- rbind(go.spec.all, c(top.dir1, go.rank, id1, go.spec1))

# Save GO region / age enrichment summary
# write.csv(go.spec.all, file = "../analysis/go_enrich/all/go.spec.all_regioncount_byage.csv")

```


```{r calc-go-synchrony, eval=FALSE}
# Load GO heatmaps
region.subset <- "toplevel"

fn1 <- paste0("../analysis/go_enrich/", region.subset, "/go.overlap.all_", 
              region.subset, "_BP.Rdata")
load(file=fn1)

# Create matrix of when/where GO terms active
m.dim <- ncol(go.overlap.all[[1]][[1]])
region.age.col <- as.list(1:m.dim)
names(region.age.col) <- colnames(go.overlap.all[[1]][[1]])

kTerms <- list(length(go.overlap.all[[1]]), 
               length(go.overlap.all[[2]]))
names(kTerms) <- names(go.overlap.all)
go.spec.all <- list(matrix(NA, kTerms[[1]], length(region.age.col), 
                           dimnames=list(names(go.overlap.all[[1]]), 
                                         names(region.age.col))), 
                    matrix(NA, kTerms[[2]], length(region.age.col), 
                           dimnames=list(names(go.overlap.all[[2]]), 
                                         names(region.age.col))))
names(go.spec.all) <- names(go.overlap.all)

for (dir1 in names(kTerms)) {
  for (term1 in 1:kTerms[[dir1]]) {
    go.overlap.combined <- go.overlap.all[[dir1]][[term1]]
    if (dir1 == "decreasing") {
      go.spec1 <- sapply(region.age.col, 
                         function(y) mean(c(go.overlap.combined[y:m.dim, y], 
                                             go.overlap.combined[y, 1:(y-1)]), 
                                           na.rm = TRUE) > 0.01)
    } else {
      go.spec1 <- sapply(region.age.col,
                         function(y) mean(c(go.overlap.combined[y, y:m.dim],
                                             go.overlap.combined[1:(y-1), y]), 
                                           na.rm = TRUE) > 0.01)
    }
    
    # Check if GO term active in all regions
    reg.cnt <- sum(sapply(c(1, 10, 19, 28), function(y) any(go.spec1[y:(y + 8)])))  # Toplevel
    if (reg.cnt < 4) {
      go.spec1 <- rep(NA, length(go.spec1))
    }
    
    # Combine results
    go.spec.all[[dir1]][term1, ] <- go.spec1
  }
  # Remove GO terms not active in all regions
  go.spec.all[[dir1]] <- na.omit(go.spec.all[[dir1]])
}


# Calc pairwise region synchrony (% ages in sync)
CalcSync <- function(x) {
  num.ages <- length(x) / 2
  # Number of ages GO process is active in BOTH regions
  sync.cnt <- sum(sapply(c(1:num.ages), 
                         function(y) x[y] + x[y + num.ages]) == 2)
#   Number of ages GO process is active in EITHER region (union of ages)
  total.cnt <- sum(sapply(c(1:num.ages), 
                          function(y) x[y] + x[y + num.ages]) > 0)
  # Number of ages GO process is active in regions
#   reg.cnt <- c(sum(sapply(c(1:9), function(y) x[y])), 
#                      sum(sapply(c(1:9), function(y) x[y + 9])))
  # Max # ages GO process is active in EITHER region (always <= union of ages)
#   total.cnt <- max(reg.cnt)
  sync.prop <- sync.cnt / total.cnt
  return(sync.prop)
}

CalcMinAge <- function(x) {
  # Earliest age GO process is active in each region
  min.ageid <- sapply(c(1, 10, 19, 28), 
                      function(y) which(x[y:(y + 8)] == TRUE)[1])
  names(min.ageid) <- c("NCX", "HP", "AM", "BG")
  return(min.ageid)
}

CalcMaxAge <- function(x) {
  # Earliest age GO process is active in each region
  max.ageid <- sapply(c(1, 10, 19, 28), 
                      function(y) max(which(x[y:(y + 8)] == TRUE)))
  names(max.ageid) <- c("NCX", "HP", "AM", "BG")
  return(max.ageid)
}

CntGo <- function(x) {
  # Reformat as matrix (ages x regions)
  x2 <- matrix(x, nrow=9, ncol=4)
  reg.cnt <- c(apply(x2, 2, sum),  # Commonality by region
               sum(apply(x2, 1, any)))  # Commonality across all regions
  return(reg.cnt)  
}


# Define all region pair comparisons
region.pairs <- list(c("NCX", "HP"), c("NCX", "AM"), c("NCX", "BG"), 
                     c("HP", "AM"), c("HP", "BG"), c("BG", "AM"))
names(region.pairs) <- sapply(region.pairs, paste, collapse="-")
go.sync.all <- list()
go.sync.all.perm <- list()
go.cnt.all <- list()
go.min.all <- list()
go.max.all <- list()

for (dir1 in names(go.spec.all)) {
  go.spec.dir <- go.spec.all[[dir1]]
  
  # Remove thalamus from analysis (since not measured at all ages)
  go.spec.dir <- go.spec.dir[, -grep("TH", colnames(go.spec.dir))]
  
  # Calc # ages
  go.cnt <- t(apply(go.spec.dir, 1, CntGo))
  colnames(go.cnt) <- c("NCX", "HP", "AM", "BG", "any_reg")
  go.cnt.all[[dir1]] <- go.cnt
  
  # Calc min/max age onset
  go.min <- t(apply(go.spec.dir, 1, CalcMinAge))
  go.min.all[[dir1]] <- go.min
  go.max <- t(apply(go.spec.dir, 1, CalcMaxAge))
  go.max.all[[dir1]] <- go.max
  
  # Calc pairwise sync
  for (pair1 in names(region.pairs)) {
    # Select region pair
    keep.cols <- which(grepl(region.pairs[[pair1]][1], colnames(go.spec.dir)) | 
                         grepl(region.pairs[[pair1]][2], colnames(go.spec.dir))) 
    go.spec.pair <- go.spec.dir[, keep.cols]
    go.sync <- apply(go.spec.pair, 1, CalcSync)
    go.sync.all[[dir1]][[pair1]] <- go.sync
    
    # Calc randomly expected sync
    row.perm <- sample(1:nrow(go.spec.pair), nrow(go.spec.pair), replace=FALSE)
    num.ages <- ncol(go.spec.pair) / 2
    go.spec.pair.perm <- cbind(go.spec.pair[, 1:num.ages], 
                               go.spec.pair[row.perm, 
                                            (num.ages + 1):(num.ages * 2)])
    go.sync.perm <- apply(go.spec.pair.perm, 1, CalcSync)
    go.sync.all.perm[[dir1]][[pair1]] <- go.sync.perm
  }
}

# Combine incr/decr data
go.spec.all.df <- rbind(data.frame(dir="increasing", 
                                   goid=rownames(go.spec.all[["increasing"]]), 
                                   go.spec.all[["increasing"]]), 
                        data.frame(dir="decreasing", 
                                   goid=rownames(go.spec.all[["decreasing"]]), 
                                   go.spec.all[["decreasing"]]))

# Annotate GO ids
go.spec.all.df$goterm <- sapply(go.spec.all.df$goid, 
                                function(goid) slot(xx[[as.character(goid)]], "Term"))

# Convert TRUE/FALSE to 0/1
go.spec.all.df[go.spec.all.df == TRUE] <- 1
go.spec.all.df[go.spec.all.df == FALSE] <- 0

# Save GO region / age enrichment summary
fn1 <- paste0("../analysis/go_enrich/", region.subset, "/go.spec.all.df_sync.csv")
# write.csv(go.spec.all.df, file = fn1, row.names=FALSE)


# Calc average synchrony and # ages for decr/incr GO terms
go.sync.avg <- data.frame()
go.sync.avg.perm <- data.frame()
go.cnt.df <- data.frame()
go.info <- list()
for (dir1 in names(go.sync.all)) {
  # Sync
  go.sync.dir <- sapply(go.sync.all[[dir1]], c)
  go.sync.avg <- rbind(go.sync.avg, 
                       data.frame(dir1, go.sync.dir, 
                                  mean_pw=apply(go.sync.dir, 1, mean)))
  # Sync (perm)
  go.sync.dir.perm <- sapply(go.sync.all.perm[[dir1]], c)
  go.sync.avg.perm <- rbind(go.sync.avg.perm, 
                            data.frame(dir1, go.sync.dir.perm, 
                                       mean_pw=apply(go.sync.dir.perm, 1, mean)))
  # Commonality
  go.cnt.df <- rbind(go.cnt.df, 
                     data.frame(dir1, go.cnt.all[[dir1]]))
  
  go.syncm <- as.data.frame(sapply(go.sync.all[[dir1]], c))
  go.syncm$go_id <- rownames(go.syncm)
  go.info[[dir1]] <- go.syncm
}

# Save GO info
# write.csv(go.sync.avg, 
#           file="../analysis/go_enrich/toplevel/go.sync.avg.csv")
# write.csv(go.sync.avg.perm, 
#           file="../analysis/go_enrich/toplevel/go.sync.avg.perm.csv")
# write.csv(go.cnt.df, 
#           file="../analysis/go_enrich/toplevel/go.cnt.df.csv")
# write.csv(go.info[["increasing"]], 
#           file="../analysis/go_enrich/toplevel/go.info_incr.csv")
# write.csv(go.info[["decreasing"]], 
#           file="../analysis/go_enrich/toplevel/go.info_decr.csv")

```


# Figure 2c, Extended Data Figure 4c
```{r plot-go-heatmaps, fig.height=8, fig.width=8, eval=TRUE}
# Load GO overlap matrices
region.subset <- "all"
fn1 <- paste0("../analysis/go_enrich/", region.subset, "/go.overlap_", 
              region.subset, "_BP.Rdata")
load(file=fn1)

pal1 <- colorRampPalette(c("white", brewer.pal(n = 9, name = "YlOrRd")), 
                         space = "rgb")(100)

plot.goids <- c("GO:0045773", "GO:0010977", "GO:0097480", 
                "GO:0050773", "GO:0006914")
for (goid in plot.goids) {
  goid.name <- paste0(goid, " ", slot(xx[[goid]], "Term"))
  go.overlap.combined <- go.overlap[[goid]]

  pheatmap(go.overlap.combined, cluster_rows = FALSE, 
           cluster_cols = FALSE, border = NA, color = pal1, 
           main = goid.name, show_rownames = FALSE, show_colnames = FALSE)
}

```


# Figure 3a
```{r plot-go-commonality, fig.width=4, fig.height=4, eval=TRUE}
go.cnt.df <- read.csv(file="../analysis/go_enrich/toplevel/go.cnt.df.csv")
go.cnt.df <- go.cnt.df[, 2:7]

# Convert dfs to long format for ggplot
go.cnt.dfl <- melt(go.cnt.df, id="dir1")
colnames(go.cnt.dfl) <- c("dir1", "region", "cnt")

# Reorder region
go.cnt.dfl$region <- factor(go.cnt.dfl$region, 
                            levels=c("NCX", "HP", "BG", "AM", "any_reg"))

# Plot GO commonality
# pal.col2 <- c(brewer.pal(4, "Set2"), "black")
pal.col2 <- c("#ca0020", "#f4a582", "#92c5de", "#0571b0", "black")
  
g2 <- ggplot(go.cnt.dfl, aes(x=cnt, y=..density.., color=region)) +
      geom_freqpoly(binwidth=1, size=2) +
  facet_grid(dir1 ~ .) +
  scale_x_discrete(breaks=1:9) +
  theme_bw() + 
  scale_color_manual(values=pal.col2) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("Commonality of GO process (# ages)")
plot(g2)

```


# Extended Data Figure 5a
```{r plot-go-sync-example, fig.width=6, fig.height=4}
ages <- c("E50", "E70", "E80", "E90", "E120", "0M", "3M", "12M", "48M")

# Load GO
region.subset <- "toplevel"
fn1 <- paste0("../analysis/go_enrich/", region.subset, "/go.spec.all.df_sync.csv")
go.spec.all.df <- read.csv(file=fn1)
go.spec.all <- subset(go.spec.all.df, dir == "increasing")
rownames(go.spec.all) <- go.spec.all$goid

go1 <- "GO:0021953"
term1 <- go.spec.all[go1, "goterm"]
go.matrix <- t(matrix(as.numeric(go.spec.all[go1, 3:38]), nrow = 9))
go.matrix[go.matrix == TRUE] <- 1
go.matrix[go.matrix == FALSE] <- 0
go.matrix <- go.matrix[c(3, 4, 2, 1), ]
rownames(go.matrix) <- c("AM", "BG", "HP", "NCX")
colnames(go.matrix) <- ages

pheatmap(go.matrix, cluster_rows = FALSE, cluster_cols = FALSE, legend = FALSE, 
         col=c("grey90", "black"), border=NA, main=paste(go1, term1))

```


# Extended Data Figure 5b
```{r plot-go-synchrony, fig.width=5, fig.height=4, eval=TRUE}
go.sync.avg <- read.csv(file="../analysis/go_enrich/toplevel/go.sync.avg.csv", 
                        row.names=1)
go.sync.avg.perm <- read.csv(file="../analysis/go_enrich/toplevel/go.sync.avg.perm.csv", 
                             row.names=1)

# Convert dfs to long format for ggplot
go.sync.avgl <- melt(go.sync.avg, id="dir1")
colnames(go.sync.avgl) <- c("dir1", "region_pair", "sync")

# Add expected synchrony (based on permuted pw comparisons)
sync.perm <- data.frame(dir1=go.sync.avg.perm$dir1,
                        region_pair="mean_pw_perm", 
                        sync=go.sync.avg.perm$mean_pw)
levels(go.sync.avgl$region_pair) <- c(levels(go.sync.avgl$region_pair), 
                                            "mean_pw_perm")
go.sync.avgl <- rbind(go.sync.avgl, sync.perm)

# Plot GO synchrony
pal.dir <- c("#0270ae", "#cd1900")  # Based on Fig. 2B incr/decr colors
pal.col <- c(brewer.pal(6, "Set2"), "black", "black")
lt <- c(rep("solid", 7), "dotted")

g1 <- ggplot(go.sync.avgl, aes(x=sync, y=..density.., 
                               color=region_pair, linetype=region_pair)) +
  geom_density(size=1, adjust=1, alpha=0.05, fill=NA) +
  facet_grid(dir1 ~ .) +  #, scales="free_y"
  theme_bw() + 
  scale_color_manual(values=pal.col) +
  scale_fill_manual(values=pal.dir) +
  scale_linetype_manual(values=lt) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("Synchrony of GO process")
plot(g1)

```


# Figure 3b, Extended Data Figure 5c
```{r plot-go-timing, fig.width=15, fig.height=10}
agepcd <- c(50, 70, 80, 90, 120, 165, 255, 530, 1625)

CalcMinAge <- function(x) {
  # Earliest age GO process is active in each region
  min.ageid <- sapply(c(1, 10, 19, 28), 
                      function(y) which(x[y:(y + 8)] == TRUE)[1])
  names(min.ageid) <- c("NCX", "HP", "AM", "BG")
  return(min.ageid)
}

# Calc min age onset
go.min.all <- list()
go.spec.dir <- go.spec.all[, 3:38]
go.min <- t(apply(go.spec.dir, 1, CalcMinAge))
go.min.all[["increasing"]] <- go.min

# Age of onset
go.async.list <- list()
go.async.list[["increasing"]] <- go.min.all[["increasing"]]

# Replace GO id with name
go.term1 <- sapply(rownames(go.async.list[[1]]), 
                   function(x) slot(xx[[x]], "Term"))

rownames(go.async.list[[1]]) <- go.term1

dir1 <- "increasing"

# Calc average start age in cortical and subcortical regions
avg.onset.age <- cbind(apply(go.async.list[[dir1]], 1, function(x) mean(agepcd[as.numeric(x[c("BG", "AM")])])),
                       apply(go.async.list[[dir1]], 1, function(x) mean(agepcd[as.numeric(x[c("NCX", "HP")])])))
colnames(avg.onset.age) <- c("Subctx", "Ctx")
rownames(avg.onset.age) <- rownames(go.async.list[[dir1]])

# Add individual region age of onset
avg.onset.age2 <- t(apply(go.async.list[[dir1]], 1, function(x) agepcd[as.numeric(x)]))
avg.onset.age2 <- t(apply(go.async.list[[dir1]], 1, function(x) as.numeric(x)))
colnames(avg.onset.age2) <- colnames(go.async.list[[dir1]])
avg.onset.age3 <- cbind(avg.onset.age, avg.onset.age2)

# Calc age rank
age.rank <- t(apply(go.async.list[[dir1]], 1, rank, ties.method = "average"))

# Count age rank patterns
age.rank.group <- apply(age.rank, 1, paste, collapse="")
table1 <- as.data.frame(table(age.rank.group))
table1$rank <- rank(-table1$Freq, ties.method = "random")
age.rank.order <- table1$rank[match(age.rank.group, table1$age.rank.group)]

# Min age onset
min.age <- apply(avg.onset.age2, 1, min)

# Calc ctx/sub-ctx timing
region.timing <- rep(1, nrow(avg.onset.age2))
ctx.early <- which(apply(avg.onset.age3[, -c(1:2)], 1, 
                         function(x) (x[1] < x[3] & x[1] < x[4]) | 
                           (x[2] < x[3] & x[2] < x[4])))
subctx.early <- which(apply(avg.onset.age3[, -c(1:2)], 1, 
                            function(x) (x[3] < x[1] & x[3] < x[2]) | 
                              (x[4] < x[1] & x[4] < x[2])))
ctx.subctx.sync <- which(apply(avg.onset.age3[, -c(1:2)], 1, function(x) sd(x) == 0))
region.timing[ctx.early] <- 2
region.timing[subctx.early] <- 3
region.timing[ctx.subctx.sync] <- 4


# Order GO terms based on onset by region
row.order <- order(min.age, avg.onset.age2[, "AM"], avg.onset.age2[, "BG"], 
                   avg.onset.age2[, "HP"], avg.onset.age2[, "NCX"], 
                   rownames(avg.onset.age))

# Reorder matrices
avg.onset.age3 <- avg.onset.age3[row.order, ]
age.rank2 <- age.rank[row.order, ]
age.rank.group <- age.rank.group[row.order]
region.timing <- region.timing[row.order]

# Plot age of onset
plot(avg.onset.age3[, "NCX"], 1:nrow(avg.onset.age3), 
     yaxt = "none", ylab = "", type = "n", 
     xlab = "", bty = "n", 
     ylim = c(0, nrow(avg.onset.age3)), xlim = c(1, 10), xaxt="n")  # c(50, 2000)
axis(1, at=1:10, c(ages, "T"), las=2)  # KLUDGE - add final age for annotation

# Birth age
  abline(v = 5.5, lty = "dashed", col = "grey80", lwd = 2)

pal.pt <- c("#ca0020", "#f4a582", "#92c5de", "#0571b0")
names(pal.pt) <- c("NCX", "HP", "BG", "AM")
cex1 <- 0.7

for (region1 in rev(c("NCX", "HP", "BG", "AM"))) {
  jitter1 <- 0.06 * (which(names(pal.pt) == region1) - 2.5)
  points(avg.onset.age3[, region1] - jitter1, 1:nrow(avg.onset.age3),
         col = pal.pt[region1], pch=15, cex=cex1)
}

# Plot region timing
pal.timing <- c("grey", "red", "blue", "black")
segments(rep(10, nrow(avg.onset.age3)) - 0.15, 1:nrow(avg.onset.age3),
         rep(10, nrow(avg.onset.age3)) + 0.15, 1:nrow(avg.onset.age3), 
         col = pal.timing[region.timing], pch=15, lwd = 0.01)

# Add legend
legend("topleft", fill = rev(pal.pt),  
       bty = "n", cex = 0.8, legend = rev(names(pal.pt)), 
       title="Age of onset")

# Plot age rank
pal1 <- colorRampPalette(c(brewer.pal(n = 9, name = "YlOrBr")))(100)
age.rank.prop <- apply(t(apply(go.async.list[[dir1]], 1, rank, ties.method = "average")), 2, table)[, c(3,4,2,1)]/nrow(go.async.list[[dir1]])
pheatmap(age.rank.prop, cluster_rows = FALSE, cluster_cols = FALSE, color = pal1, border=NA)

# Calc weighted mean age rank by region (overlay on heatmap)
age.rank.mean <- apply(age.rank.prop, 2, 
                       function(x) weighted.mean(c(1, 1.5, 2, 2.5, 3, 3.5, 4), x))
plot(1:4, age.rank.mean, ylim=c(4, 1), xaxt="none", type="b", las=1, 
     xlab = "Region", ylab = "Onset (average rank)")
axis(1, at = 1:4, labels = c("AM", "BG", "HP", "NCX"))

```
