---
output: 
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
# Set default knitr options
knitr::opts_chunk$set(cache = FALSE,  # Cache all chunks
                      echo = FALSE,  # Hide output
                      dev = c("png", "pdf"))  # Figure formats to output

# If cached chunk is changed, auto-update all following chunks
knitr::dep_prev()

# Define knitr functions
fGetmtime <- function(files) {
  lapply(Sys.glob(files), function(x) file.info(x)$mtime)
}
```


```{r init-workspace, echo=FALSE, message=FALSE, warning=FALSE}
# Set environment
options(StringsAsFactors = FALSE)

# Load libraries
library(RColorBrewer)
library(ggplot2)
library(reshape2)

# Load functions
source(file = "../src/fReorderFactorLevels.R")
```

```{r load-data}
# Load macaque starting data
load(file = "../cache/nhp_PrePost_StartingData.RData")

# Load macaque expr change (cortex by area/layer)
load(file = "../cache/expr_dynamics/expr.summary.bystruc.long_NCXlayer_dev.RData")

```


```{r process-data}
# Extract cortical area/layer info
ctx.region <- gsub("_.*$", "", expr.summary.bystruc.long$struc)
ctx.layer <- gsub("^.*_", "", expr.summary.bystruc.long$struc)
expr.summary.bystruc.long$area <- ctx.region
expr.summary.bystruc.long$layer <- ctx.layer

# Reorder factor levels
age.order <- c("E40", "E50", "E70", "E80", "E90", "E120", 
               "0M", "3M", "12M", "48M")
age1 <- ReorderFactorLevels(expr.summary.bystruc.long$age, 
                            level.order = age.order, ordered = TRUE)
expr.summary.bystruc.long$age <- age1

layer.order <- rev(c("Hem", "WM", "VZi", "VZo", "VZ", "SZi", "SZo", "SZ", 
                 "IZ", "IFZ", "TMZ", "OFZ", "ICD", "SP", "CPi", "L6", "L5", 
                 "CPo", "CP", "L4", "L4Cb", "L4Ca", "L4B", "L4A", 
                 "L3", "L2-3", "L2.3", "L2", "L1", "MZ"))
layer1 <- ReorderFactorLevels(expr.summary.bystruc.long$layer, 
                            level.order = layer.order, ordered = FALSE)
expr.summary.bystruc.long$layer <- layer1

# Make MZ/L1 and IZ/WM continuous across time (KLUDGE)
expr.summary.bystruc.long$layer[expr.summary.bystruc.long$layer == "L1"] <- "MZ"
mz1 <- subset(expr.summary.bystruc.long, area == "V1" & 
                age == "0M" & layer == "L2")
mz1$layer <- "MZ"
expr.summary.bystruc.long$layer[expr.summary.bystruc.long$layer == "WM"] <- "IZ"
iz1 <- subset(expr.summary.bystruc.long, area == "V1" & 
                age == "0M" & layer == "L6")
iz1$layer <- "IZ"

# KLUDGE - assume rates of change in MZ/IZ similar to L2/L6
expr.summary.bystruc.long <- rbind(expr.summary.bystruc.long, mz1, iz1)

# Keep ACG, V1 with expr rate info
keep.layers <- c("VZ", "SZ", "IZ", "SP", "L6", "L5", 
                 "L4", "L3", "L2", "MZ", "Macaque", "WM", "L1")
keep.areas <- c("ACG", "V1")  # S1
keep.struc <- with(expr.summary.bystruc.long, 
                   which(layer %in% keep.layers & 
                           !is.na(expr_diff_rate) &  # Remove E40, etc.
                           area %in% keep.areas))
expr.summary.bystruc.long <- droplevels(expr.summary.bystruc.long[keep.struc, ])
```


```{r process-expr-data}
# Keep V1/ACG
subset1 <- with(samplePrePost, 
                which(subregion %in% keep.areas & 
                        layer_dev %in% keep.layers))
expr.subset <- as.data.frame(exprPrePost[, subset1])
expr.subset$gene <- probes$macaque_genesymbol
sample.subset <- droplevels(samplePrePost[subset1, ])

# Reshape expr data to long format
exprl <- melt(expr.subset, id="gene")
row.id <- match(exprl$variable, rownames(sample.subset))
keep.cols <- c("age", "subregion", "layer_dev")
exprl2 <- data.frame(exprl, sample.subset[row.id, keep.cols])

# Rename columns to match previous ggplot command
colnames(exprl2) <- c("gene", "sample_id", "expr", "age", "area", "layer")

# Combine MZ/L1 and IZ/WM
exprl2$layer <- as.character(exprl2$layer)
exprl2$layer[exprl2$layer %in% c("MZ", "L1")] <- "MZ_L1"
exprl2$layer[exprl2$layer %in% c("IZ", "WM")] <- "IZ_WM"

# Reorder layers
layer.order <- rev(c("Hem", "WM", "VZi", "VZo", "VZ", "SZi", "SZo", "SZ", 
                 "IZ", "IZ_WM", "IFZ", "TMZ", "OFZ", "ICD", "SP", "CPi", 
                 "L6", "L5", "CPo", "CP", "L4", "L4Cb", "L4Ca", "L4B", "L4A", 
                 "L3", "L2-3", "L2.3", "L2", "L1", "MZ", "MZ_L1"))
layer1 <- ReorderFactorLevels(exprl2$layer, level.order = layer.order, 
                              ordered = FALSE)
exprl2$layer <- layer1

```


# Figure 5b-f
```{r plot-gene-bylayer, fig.width=4, fig.height=12, message=FALSE, warning=FALSE, eval=TRUE}

num.timepoints <- length(table(exprl2$age))
pd <- position_dodge(width = 0.4)

# Pick gene(s) to plot
gene.ids <- match(c("MKI67", "GAD1", "LOC713917", "AQP4", "FGFR3", "CBLN2"), 
                  probes$macaque_genesymbol)

for (i in gene.ids) {  # 1:nrow(probes)
  m.gene <- probes$macaque_genesymbol[i]
  # Add human ortholog symbol
  m.gene.title <- ifelse(m.gene == "LOC713917", "NGEF (LOC713917)", m.gene)
  m.probe <- probes$probeid[i]
  m.id <- probes$macaque_entrezid[i]
  m.ortho <- probes$human_genesymbol[i]
  if (is.na(m.ortho)) m.ortho <- "_"
  
  # Select gene data
  exprl2.subset <- subset(exprl2, gene == m.gene)
  exprl2.subset <- droplevels(exprl2.subset)
  
  f.name <- paste(m.gene, m.ortho, m.id, m.probe, sep="_")
  
  p1 <- ggplot(data = exprl2.subset, 
               aes(x = as.numeric(age), y = expr, 
                   color=area, fill=area, shape=area)) + 
    facet_grid(layer ~ .) + 
    stat_summary(fun.y = mean, geom = "line", position=pd) +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", mult=1, position=pd) +
    xlab("Age") + 
    ylab("log2(Expression)") +
    ggtitle(m.gene.title) +
    scale_x_continuous(breaks = 1:num.timepoints, 
                     labels = levels(exprl2$age)) +
    scale_color_manual(values=c("#f8766d", "#619cff", "#00ba38")) +
    theme_bw() + theme(axis.text.x = element_text(angle=45),
                       axis.text = element_text(size=9),
                       panel.grid.minor = element_blank())
  
  plot(p1)
#   ggsave(plot=p1, file = paste0("../analysis/gene_plots/", f.name, ".pdf"), 
#          width=4, height=12) 
}

```


